/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import zt.cms.xf.common.dao.XfcontractpaysDao;
import zt.cms.xf.common.dto.Xfcontractpays;
import zt.cms.xf.common.exceptions.XfcontractpaysDaoException;
import zt.cms.xf.common.factory.XfcontractpaysDaoFactory;

public class XfcontractpaysDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereContractnoEquals("");
		// findWhereCpaamtEquals(null);
		// findWhereStartdateEquals(null);
		// findWhereGraceperiodEquals(null);
		// findWherePoanoEquals(null);
		// findWherePaybackactEquals("");
		// findWhereRecvactEquals("");
		// findWhereCpatypeEquals(null);
		// findWherePaybackbankidEquals("");
		// findWherePaybackbanknoEquals("");
		// findWhereRecvbankidEquals("");
		// findWhereRecvbanknoEquals("");
		// findWhereCreatoridEquals("");
		// findWhereCreatedateEquals(null);
		// findWhereCreateformEquals("");
		// findWhereUpdatoridEquals("");
		// findWhereUpdatedateEquals(null);
		// findWhereUpdateformEquals("");
		// findWherePaybackactnameEquals("");
		// findWherePrincipalamtEquals(null);
		// findWhereServicechargefeeEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContractnoEquals'
	 * 
	 * @param contractno
	 */
	public static void findWhereContractnoEquals(String contractno)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereContractnoEquals(contractno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCpaamtEquals'
	 * 
	 * @param cpaamt
	 */
	public static void findWhereCpaamtEquals(BigDecimal cpaamt)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereCpaamtEquals(cpaamt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStartdateEquals'
	 * 
	 * @param startdate
	 */
	public static void findWhereStartdateEquals(Date startdate)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereStartdateEquals(startdate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereGraceperiodEquals'
	 * 
	 * @param graceperiod
	 */
	public static void findWhereGraceperiodEquals(BigDecimal graceperiod)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereGraceperiodEquals(graceperiod);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePoanoEquals'
	 * 
	 * @param poano
	 */
	public static void findWherePoanoEquals(BigDecimal poano)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWherePoanoEquals(poano);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackactEquals'
	 * 
	 * @param paybackact
	 */
	public static void findWherePaybackactEquals(String paybackact)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWherePaybackactEquals(paybackact);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRecvactEquals'
	 * 
	 * @param recvact
	 */
	public static void findWhereRecvactEquals(String recvact)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereRecvactEquals(recvact);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCpatypeEquals'
	 * 
	 * @param cpatype
	 */
	public static void findWhereCpatypeEquals(BigDecimal cpatype)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereCpatypeEquals(cpatype);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackbankidEquals'
	 * 
	 * @param paybackbankid
	 */
	public static void findWherePaybackbankidEquals(String paybackbankid)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWherePaybackbankidEquals(paybackbankid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackbanknoEquals'
	 * 
	 * @param paybackbankno
	 */
	public static void findWherePaybackbanknoEquals(String paybackbankno)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWherePaybackbanknoEquals(paybackbankno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRecvbankidEquals'
	 * 
	 * @param recvbankid
	 */
	public static void findWhereRecvbankidEquals(String recvbankid)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereRecvbankidEquals(recvbankid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRecvbanknoEquals'
	 * 
	 * @param recvbankno
	 */
	public static void findWhereRecvbanknoEquals(String recvbankno)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereRecvbanknoEquals(recvbankno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreatoridEquals'
	 * 
	 * @param creatorid
	 */
	public static void findWhereCreatoridEquals(String creatorid)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereCreatoridEquals(creatorid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreatedateEquals'
	 * 
	 * @param createdate
	 */
	public static void findWhereCreatedateEquals(Date createdate)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereCreatedateEquals(createdate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreateformEquals'
	 * 
	 * @param createform
	 */
	public static void findWhereCreateformEquals(String createform)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereCreateformEquals(createform);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdatoridEquals'
	 * 
	 * @param updatorid
	 */
	public static void findWhereUpdatoridEquals(String updatorid)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereUpdatoridEquals(updatorid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdatedateEquals'
	 * 
	 * @param updatedate
	 */
	public static void findWhereUpdatedateEquals(Date updatedate)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereUpdatedateEquals(updatedate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdateformEquals'
	 * 
	 * @param updateform
	 */
	public static void findWhereUpdateformEquals(String updateform)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereUpdateformEquals(updateform);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackactnameEquals'
	 * 
	 * @param paybackactname
	 */
	public static void findWherePaybackactnameEquals(String paybackactname)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWherePaybackactnameEquals(paybackactname);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrincipalamtEquals'
	 * 
	 * @param principalamt
	 */
	public static void findWherePrincipalamtEquals(BigDecimal principalamt)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWherePrincipalamtEquals(principalamt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereServicechargefeeEquals'
	 * 
	 * @param servicechargefee
	 */
	public static void findWhereServicechargefeeEquals(BigDecimal servicechargefee)
	{
		try {
			XfcontractpaysDao _dao = getXfcontractpaysDao();
			Xfcontractpays _result[] = _dao.findWhereServicechargefeeEquals(servicechargefee);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getXfcontractpaysDao'
	 * 
	 * @return XfcontractpaysDao
	 */
	public static XfcontractpaysDao getXfcontractpaysDao()
	{
		return XfcontractpaysDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Xfcontractpays dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getContractno() );
		buf.append( ", " );
		buf.append( dto.getCpaamt() );
		buf.append( ", " );
		buf.append( dto.getStartdate() );
		buf.append( ", " );
		buf.append( dto.getGraceperiod() );
		buf.append( ", " );
		buf.append( dto.getPoano() );
		buf.append( ", " );
		buf.append( dto.getPaybackact() );
		buf.append( ", " );
		buf.append( dto.getRecvact() );
		buf.append( ", " );
		buf.append( dto.getCpatype() );
		buf.append( ", " );
		buf.append( dto.getPaybackbankid() );
		buf.append( ", " );
		buf.append( dto.getPaybackbankno() );
		buf.append( ", " );
		buf.append( dto.getRecvbankid() );
		buf.append( ", " );
		buf.append( dto.getRecvbankno() );
		buf.append( ", " );
		buf.append( dto.getCreatorid() );
		buf.append( ", " );
		buf.append( dto.getCreatedate() );
		buf.append( ", " );
		buf.append( dto.getCreateform() );
		buf.append( ", " );
		buf.append( dto.getUpdatorid() );
		buf.append( ", " );
		buf.append( dto.getUpdatedate() );
		buf.append( ", " );
		buf.append( dto.getUpdateform() );
		buf.append( ", " );
		buf.append( dto.getPaybackactname() );
		buf.append( ", " );
		buf.append( dto.getPrincipalamt() );
		buf.append( ", " );
		buf.append( dto.getServicechargefee() );
		System.out.println( buf.toString() );
	}

}
