/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import zt.cms.xf.common.dao.XfvcutpaydetlDao;
import zt.cms.xf.common.dto.Xfvcutpaydetl;
import zt.cms.xf.common.exceptions.XfvcutpaydetlDaoException;
import zt.cms.xf.common.factory.XfvcutpaydetlDaoFactory;

public class XfvcutpaydetlDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereJournalnoEquals("");
		// findWhereContractnoEquals("");
		// findWherePoanoEquals(null);
		// findWhereBillstatusEquals("");
		// findWhereEnudtEquals("");
		// findWhereRecvbankidEquals("");
		// findWhereRecvactEquals("");
		// findWherePaybackactEquals("");
		// findWherePaybackbankidEquals("");
		// findWherePaybackdateEquals(null);
		// findWherePaidupamtEquals(null);
		// findWhereAppnoEquals("");
		// findWherePartnernameEquals("");
		// findWhereClientnameEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereJournalnoEquals'
	 * 
	 * @param journalno
	 */
	public static void findWhereJournalnoEquals(String journalno)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result = _dao.findWhereJournalnoEquals(journalno);
			display( _result );
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContractnoEquals'
	 * 
	 * @param contractno
	 */
	public static void findWhereContractnoEquals(String contractno)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereContractnoEquals(contractno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePoanoEquals'
	 * 
	 * @param poano
	 */
	public static void findWherePoanoEquals(BigDecimal poano)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWherePoanoEquals(poano);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBillstatusEquals'
	 * 
	 * @param billstatus
	 */
	public static void findWhereBillstatusEquals(String billstatus)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereBillstatusEquals(billstatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEnudtEquals'
	 * 
	 * @param enudt
	 */
	public static void findWhereEnudtEquals(String enudt)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereEnudtEquals(enudt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRecvbankidEquals'
	 * 
	 * @param recvbankid
	 */
	public static void findWhereRecvbankidEquals(String recvbankid)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereRecvbankidEquals(recvbankid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRecvactEquals'
	 * 
	 * @param recvact
	 */
	public static void findWhereRecvactEquals(String recvact)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereRecvactEquals(recvact);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackactEquals'
	 * 
	 * @param paybackact
	 */
	public static void findWherePaybackactEquals(String paybackact)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWherePaybackactEquals(paybackact);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackbankidEquals'
	 * 
	 * @param paybackbankid
	 */
	public static void findWherePaybackbankidEquals(String paybackbankid)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWherePaybackbankidEquals(paybackbankid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaybackdateEquals'
	 * 
	 * @param paybackdate
	 */
	public static void findWherePaybackdateEquals(Date paybackdate)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWherePaybackdateEquals(paybackdate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaidupamtEquals'
	 * 
	 * @param paidupamt
	 */
	public static void findWherePaidupamtEquals(BigDecimal paidupamt)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWherePaidupamtEquals(paidupamt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAppnoEquals'
	 * 
	 * @param appno
	 */
	public static void findWhereAppnoEquals(String appno)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereAppnoEquals(appno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePartnernameEquals'
	 * 
	 * @param partnername
	 */
	public static void findWherePartnernameEquals(String partnername)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWherePartnernameEquals(partnername);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereClientnameEquals'
	 * 
	 * @param clientname
	 */
	public static void findWhereClientnameEquals(String clientname)
	{
		try {
			XfvcutpaydetlDao _dao = getXfvcutpaydetlDao();
			Xfvcutpaydetl _result[] = _dao.findWhereClientnameEquals(clientname);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getXfvcutpaydetlDao'
	 * 
	 * @return XfvcutpaydetlDao
	 */
	public static XfvcutpaydetlDao getXfvcutpaydetlDao()
	{
		return XfvcutpaydetlDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Xfvcutpaydetl dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getJournalno() );
		buf.append( ", " );
		buf.append( dto.getContractno() );
		buf.append( ", " );
		buf.append( dto.getPoano() );
		buf.append( ", " );
		buf.append( dto.getBillstatus() );
		buf.append( ", " );
		buf.append( dto.getRecvbankid() );
		buf.append( ", " );
		buf.append( dto.getRecvact() );
		buf.append( ", " );
		buf.append( dto.getPaybackact() );
		buf.append( ", " );
		buf.append( dto.getPaybackbankid() );
		buf.append( ", " );
		buf.append( dto.getPaybackdate() );
		buf.append( ", " );
		buf.append( dto.getPaidupamt() );
		buf.append( ", " );
		buf.append( dto.getAppno() );
		buf.append( ", " );
		buf.append( dto.getPartnername() );
		buf.append( ", " );
		buf.append( dto.getClientname() );
		buf.append( ", " );
		buf.append( dto.getPaybackamt() );
		buf.append( ", " );
		buf.append( dto.getPartnerbankname() );
		buf.append( ", " );
		buf.append( dto.getPaybackbankname() );
		System.out.println( buf.toString() );
	}

}
