/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import zt.cms.xf.common.dao.FdactnoinfoDao;
import zt.cms.xf.common.dto.Fdactnoinfo;
import zt.cms.xf.common.exceptions.FdactnoinfoDaoException;
import zt.cms.xf.common.factory.FdactnoinfoDaoFactory;

public class FdactnoinfoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereActnoEquals("");
		// findWhereCutpayactnoEquals("");
		// findWhereContractnoEquals("");
		// findWhereNameEquals("");
		// findWhereStartdateEquals(null);
		// findWhereEnddateEquals(null);
		// findWhereActnostatusEquals("");
		// findWhereCreatoridEquals("");
		// findWhereCreatedateEquals(null);
		// findWhereCreateformEquals("");
		// findWhereUpdatoridEquals("");
		// findWhereUpdatedateEquals(null);
		// findWhereUpdateformEquals("");
		// findWhereRegioncdEquals("");
		// findWhereBankcdEquals("");
		// findWhereCustomeridEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereActnoEquals'
	 * 
	 * @param actno
	 */
	public static void findWhereActnoEquals(String actno)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereActnoEquals(actno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCutpayactnoEquals'
	 * 
	 * @param cutpayactno
	 */
	public static void findWhereCutpayactnoEquals(String cutpayactno)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereCutpayactnoEquals(cutpayactno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContractnoEquals'
	 * 
	 * @param contractno
	 */
	public static void findWhereContractnoEquals(String contractno)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereContractnoEquals(contractno);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStartdateEquals'
	 * 
	 * @param startdate
	 */
	public static void findWhereStartdateEquals(Date startdate)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereStartdateEquals(startdate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEnddateEquals'
	 * 
	 * @param enddate
	 */
	public static void findWhereEnddateEquals(Date enddate)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereEnddateEquals(enddate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereActnostatusEquals'
	 * 
	 * @param actnostatus
	 */
	public static void findWhereActnostatusEquals(String actnostatus)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereActnostatusEquals(actnostatus);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreatoridEquals'
	 * 
	 * @param creatorid
	 */
	public static void findWhereCreatoridEquals(String creatorid)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereCreatoridEquals(creatorid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreatedateEquals'
	 * 
	 * @param createdate
	 */
	public static void findWhereCreatedateEquals(Date createdate)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereCreatedateEquals(createdate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreateformEquals'
	 * 
	 * @param createform
	 */
	public static void findWhereCreateformEquals(String createform)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereCreateformEquals(createform);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdatoridEquals'
	 * 
	 * @param updatorid
	 */
	public static void findWhereUpdatoridEquals(String updatorid)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereUpdatoridEquals(updatorid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdatedateEquals'
	 * 
	 * @param updatedate
	 */
	public static void findWhereUpdatedateEquals(Date updatedate)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereUpdatedateEquals(updatedate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdateformEquals'
	 * 
	 * @param updateform
	 */
	public static void findWhereUpdateformEquals(String updateform)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereUpdateformEquals(updateform);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRegioncdEquals'
	 * 
	 * @param regioncd
	 */
	public static void findWhereRegioncdEquals(String regioncd)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereRegioncdEquals(regioncd);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBankcdEquals'
	 * 
	 * @param bankcd
	 */
	public static void findWhereBankcdEquals(String bankcd)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereBankcdEquals(bankcd);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCustomeridEquals'
	 * 
	 * @param customerid
	 */
	public static void findWhereCustomeridEquals(String customerid)
	{
		try {
			FdactnoinfoDao _dao = getFdactnoinfoDao();
			Fdactnoinfo _result[] = _dao.findWhereCustomeridEquals(customerid);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getFdactnoinfoDao'
	 * 
	 * @return FdactnoinfoDao
	 */
	public static FdactnoinfoDao getFdactnoinfoDao()
	{
		return FdactnoinfoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Fdactnoinfo dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getActno() );
		buf.append( ", " );
		buf.append( dto.getCutpayactno() );
		buf.append( ", " );
		buf.append( dto.getContractno() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getStartdate() );
		buf.append( ", " );
		buf.append( dto.getEnddate() );
		buf.append( ", " );
		buf.append( dto.getActnostatus() );
		buf.append( ", " );
		buf.append( dto.getCreatorid() );
		buf.append( ", " );
		buf.append( dto.getCreatedate() );
		buf.append( ", " );
		buf.append( dto.getCreateform() );
		buf.append( ", " );
		buf.append( dto.getUpdatorid() );
		buf.append( ", " );
		buf.append( dto.getUpdatedate() );
		buf.append( ", " );
		buf.append( dto.getUpdateform() );
		buf.append( ", " );
		buf.append( dto.getRegioncd() );
		buf.append( ", " );
		buf.append( dto.getBankcd() );
		buf.append( ", " );
		buf.append( dto.getCustomerid() );
		System.out.println( buf.toString() );
	}

}
