/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import zt.cms.xf.common.dao.*;
import zt.cms.xf.common.factory.*;
import zt.cms.xf.common.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.math.BigDecimal;
import java.util.Date;

public class Xfifbankdetl implements Serializable
{
	/** 
	 * This attribute maps to the column JOURNALNO in the XFIFBANKDETL table.
	 */
	protected String journalno;

	/** 
	 * This attribute maps to the column TXNDATE in the XFIFBANKDETL table.
	 */
	protected String txndate;

	/** 
	 * This attribute maps to the column TXNTYPE in the XFIFBANKDETL table.
	 */
	protected String txntype;

	/** 
	 * This attribute maps to the column TOTALCOUNT in the XFIFBANKDETL table.
	 */
	protected BigDecimal totalcount;

	/** 
	 * This attribute maps to the column CURRCOUNT in the XFIFBANKDETL table.
	 */
	protected BigDecimal currcount;

	/** 
	 * This attribute maps to the column MULTIFLAG in the XFIFBANKDETL table.
	 */
	protected String multiflag;

	/** 
	 * This attribute maps to the column TRANSFERACT in the XFIFBANKDETL table.
	 */
	protected String transferact;

	/** 
	 * This attribute maps to the column TOTALAMT in the XFIFBANKDETL table.
	 */
	protected BigDecimal totalamt;

	/** 
	 * This attribute maps to the column FAILAMT in the XFIFBANKDETL table.
	 */
	protected BigDecimal failamt;

	/** 
	 * This attribute maps to the column FAILCOUNT in the XFIFBANKDETL table.
	 */
	protected BigDecimal failcount;

	/** 
	 * This attribute maps to the column USAGE in the XFIFBANKDETL table.
	 */
	protected String usage;

	/** 
	 * This attribute maps to the column REMARK in the XFIFBANKDETL table.
	 */
	protected String remark;

	/** 
	 * This attribute maps to the column REMARK1 in the XFIFBANKDETL table.
	 */
	protected String remark1;

	/** 
	 * This attribute maps to the column REMARK2 in the XFIFBANKDETL table.
	 */
	protected String remark2;

	/** 
	 * This attribute maps to the column STARTDATE in the XFIFBANKDETL table.
	 */
	protected Date startdate;

	/** 
	 * This attribute maps to the column STATUS in the XFIFBANKDETL table.
	 */
	protected String status;

	/** 
	 * This attribute maps to the column BANKID in the XFIFBANKDETL table.
	 */
	protected String bankid;

	/** 
	 * This attribute maps to the column SYSTEMTYPE in the XFIFBANKDETL table.
	 */
	protected String systemtype;

	/** 
	 * This attribute maps to the column OPERATORID in the XFIFBANKDETL table.
	 */
	protected String operatorid;

	/** 
	 * This attribute maps to the column OPERATEDATE in the XFIFBANKDETL table.
	 */
	protected Date operatedate;

	/** 
	 * This attribute maps to the column CHECKERID in the XFIFBANKDETL table.
	 */
	protected String checkerid;

	/** 
	 * This attribute maps to the column CHECKDATE in the XFIFBANKDETL table.
	 */
	protected Date checkdate;

	/** 
	 * This attribute maps to the column CREATORID in the XFIFBANKDETL table.
	 */
	protected String creatorid;

	/** 
	 * This attribute maps to the column CREATEDATE in the XFIFBANKDETL table.
	 */
	protected Date createdate;

	/** 
	 * This attribute maps to the column CREATEFORM in the XFIFBANKDETL table.
	 */
	protected String createform;

	/** 
	 * This attribute maps to the column UPDATORID in the XFIFBANKDETL table.
	 */
	protected String updatorid;

	/** 
	 * This attribute maps to the column UPDATEDATE in the XFIFBANKDETL table.
	 */
	protected Date updatedate;

	/** 
	 * This attribute maps to the column UPDATEFORM in the XFIFBANKDETL table.
	 */
	protected String updateform;

	/** 
	 * This attribute maps to the column BIZSEQNO in the XFIFBANKDETL table.
	 */
	protected String bizseqno;

	/** 
	 * This attribute maps to the column DATA in the XFIFBANKDETL table.
	 */
	protected String data;

	/** 
	 * This attribute maps to the column LOG in the XFIFBANKDETL table.
	 */
	protected String log;

	/**
	 * Method 'Xfifbankdetl'
	 * 
	 */
	public Xfifbankdetl()
	{
	}

	/**
	 * Method 'getJournalno'
	 * 
	 * @return String
	 */
	public String getJournalno()
	{
		return journalno;
	}

	/**
	 * Method 'setJournalno'
	 * 
	 * @param journalno
	 */
	public void setJournalno(String journalno)
	{
		this.journalno = journalno;
	}

	/**
	 * Method 'getTxndate'
	 * 
	 * @return String
	 */
	public String getTxndate()
	{
		return txndate;
	}

	/**
	 * Method 'setTxndate'
	 * 
	 * @param txndate
	 */
	public void setTxndate(String txndate)
	{
		this.txndate = txndate;
	}

	/**
	 * Method 'getTxntype'
	 * 
	 * @return String
	 */
	public String getTxntype()
	{
		return txntype;
	}

	/**
	 * Method 'setTxntype'
	 * 
	 * @param txntype
	 */
	public void setTxntype(String txntype)
	{
		this.txntype = txntype;
	}

	/**
	 * Method 'getTotalcount'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getTotalcount()
	{
		return totalcount;
	}

	/**
	 * Method 'setTotalcount'
	 * 
	 * @param totalcount
	 */
	public void setTotalcount(BigDecimal totalcount)
	{
		this.totalcount = totalcount;
	}

	/**
	 * Method 'getCurrcount'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getCurrcount()
	{
		return currcount;
	}

	/**
	 * Method 'setCurrcount'
	 * 
	 * @param currcount
	 */
	public void setCurrcount(BigDecimal currcount)
	{
		this.currcount = currcount;
	}

	/**
	 * Method 'getMultiflag'
	 * 
	 * @return String
	 */
	public String getMultiflag()
	{
		return multiflag;
	}

	/**
	 * Method 'setMultiflag'
	 * 
	 * @param multiflag
	 */
	public void setMultiflag(String multiflag)
	{
		this.multiflag = multiflag;
	}

	/**
	 * Method 'getTransferact'
	 * 
	 * @return String
	 */
	public String getTransferact()
	{
		return transferact;
	}

	/**
	 * Method 'setTransferact'
	 * 
	 * @param transferact
	 */
	public void setTransferact(String transferact)
	{
		this.transferact = transferact;
	}

	/**
	 * Method 'getTotalamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getTotalamt()
	{
		return totalamt;
	}

	/**
	 * Method 'setTotalamt'
	 * 
	 * @param totalamt
	 */
	public void setTotalamt(BigDecimal totalamt)
	{
		this.totalamt = totalamt;
	}

	/**
	 * Method 'getFailamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getFailamt()
	{
		return failamt;
	}

	/**
	 * Method 'setFailamt'
	 * 
	 * @param failamt
	 */
	public void setFailamt(BigDecimal failamt)
	{
		this.failamt = failamt;
	}

	/**
	 * Method 'getFailcount'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getFailcount()
	{
		return failcount;
	}

	/**
	 * Method 'setFailcount'
	 * 
	 * @param failcount
	 */
	public void setFailcount(BigDecimal failcount)
	{
		this.failcount = failcount;
	}

	/**
	 * Method 'getUsage'
	 * 
	 * @return String
	 */
	public String getUsage()
	{
		return usage;
	}

	/**
	 * Method 'setUsage'
	 * 
	 * @param usage
	 */
	public void setUsage(String usage)
	{
		this.usage = usage;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'getRemark1'
	 * 
	 * @return String
	 */
	public String getRemark1()
	{
		return remark1;
	}

	/**
	 * Method 'setRemark1'
	 * 
	 * @param remark1
	 */
	public void setRemark1(String remark1)
	{
		this.remark1 = remark1;
	}

	/**
	 * Method 'getRemark2'
	 * 
	 * @return String
	 */
	public String getRemark2()
	{
		return remark2;
	}

	/**
	 * Method 'setRemark2'
	 * 
	 * @param remark2
	 */
	public void setRemark2(String remark2)
	{
		this.remark2 = remark2;
	}

	/**
	 * Method 'getStartdate'
	 * 
	 * @return Date
	 */
	public Date getStartdate()
	{
		return startdate;
	}

	/**
	 * Method 'setStartdate'
	 * 
	 * @param startdate
	 */
	public void setStartdate(Date startdate)
	{
		this.startdate = startdate;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return String
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(String status)
	{
		this.status = status;
	}

	/**
	 * Method 'getBankid'
	 * 
	 * @return String
	 */
	public String getBankid()
	{
		return bankid;
	}

	/**
	 * Method 'setBankid'
	 * 
	 * @param bankid
	 */
	public void setBankid(String bankid)
	{
		this.bankid = bankid;
	}

	/**
	 * Method 'getSystemtype'
	 * 
	 * @return String
	 */
	public String getSystemtype()
	{
		return systemtype;
	}

	/**
	 * Method 'setSystemtype'
	 * 
	 * @param systemtype
	 */
	public void setSystemtype(String systemtype)
	{
		this.systemtype = systemtype;
	}

	/**
	 * Method 'getOperatorid'
	 * 
	 * @return String
	 */
	public String getOperatorid()
	{
		return operatorid;
	}

	/**
	 * Method 'setOperatorid'
	 * 
	 * @param operatorid
	 */
	public void setOperatorid(String operatorid)
	{
		this.operatorid = operatorid;
	}

	/**
	 * Method 'getOperatedate'
	 * 
	 * @return Date
	 */
	public Date getOperatedate()
	{
		return operatedate;
	}

	/**
	 * Method 'setOperatedate'
	 * 
	 * @param operatedate
	 */
	public void setOperatedate(Date operatedate)
	{
		this.operatedate = operatedate;
	}

	/**
	 * Method 'getCheckerid'
	 * 
	 * @return String
	 */
	public String getCheckerid()
	{
		return checkerid;
	}

	/**
	 * Method 'setCheckerid'
	 * 
	 * @param checkerid
	 */
	public void setCheckerid(String checkerid)
	{
		this.checkerid = checkerid;
	}

	/**
	 * Method 'getCheckdate'
	 * 
	 * @return Date
	 */
	public Date getCheckdate()
	{
		return checkdate;
	}

	/**
	 * Method 'setCheckdate'
	 * 
	 * @param checkdate
	 */
	public void setCheckdate(Date checkdate)
	{
		this.checkdate = checkdate;
	}

	/**
	 * Method 'getCreatorid'
	 * 
	 * @return String
	 */
	public String getCreatorid()
	{
		return creatorid;
	}

	/**
	 * Method 'setCreatorid'
	 * 
	 * @param creatorid
	 */
	public void setCreatorid(String creatorid)
	{
		this.creatorid = creatorid;
	}

	/**
	 * Method 'getCreatedate'
	 * 
	 * @return Date
	 */
	public Date getCreatedate()
	{
		return createdate;
	}

	/**
	 * Method 'setCreatedate'
	 * 
	 * @param createdate
	 */
	public void setCreatedate(Date createdate)
	{
		this.createdate = createdate;
	}

	/**
	 * Method 'getCreateform'
	 * 
	 * @return String
	 */
	public String getCreateform()
	{
		return createform;
	}

	/**
	 * Method 'setCreateform'
	 * 
	 * @param createform
	 */
	public void setCreateform(String createform)
	{
		this.createform = createform;
	}

	/**
	 * Method 'getUpdatorid'
	 * 
	 * @return String
	 */
	public String getUpdatorid()
	{
		return updatorid;
	}

	/**
	 * Method 'setUpdatorid'
	 * 
	 * @param updatorid
	 */
	public void setUpdatorid(String updatorid)
	{
		this.updatorid = updatorid;
	}

	/**
	 * Method 'getUpdatedate'
	 * 
	 * @return Date
	 */
	public Date getUpdatedate()
	{
		return updatedate;
	}

	/**
	 * Method 'setUpdatedate'
	 * 
	 * @param updatedate
	 */
	public void setUpdatedate(Date updatedate)
	{
		this.updatedate = updatedate;
	}

	/**
	 * Method 'getUpdateform'
	 * 
	 * @return String
	 */
	public String getUpdateform()
	{
		return updateform;
	}

	/**
	 * Method 'setUpdateform'
	 * 
	 * @param updateform
	 */
	public void setUpdateform(String updateform)
	{
		this.updateform = updateform;
	}

	/**
	 * Method 'getBizseqno'
	 * 
	 * @return String
	 */
	public String getBizseqno()
	{
		return bizseqno;
	}

	/**
	 * Method 'setBizseqno'
	 * 
	 * @param bizseqno
	 */
	public void setBizseqno(String bizseqno)
	{
		this.bizseqno = bizseqno;
	}

	/**
	 * Method 'getData'
	 * 
	 * @return String
	 */
	public String getData()
	{
		return data;
	}

	/**
	 * Method 'setData'
	 * 
	 * @param data
	 */
	public void setData(String data)
	{
		this.data = data;
	}

	/**
	 * Method 'getLog'
	 * 
	 * @return String
	 */
	public String getLog()
	{
		return log;
	}

	/**
	 * Method 'setLog'
	 * 
	 * @param log
	 */
	public void setLog(String log)
	{
		this.log = log;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Xfifbankdetl)) {
			return false;
		}
		
		final Xfifbankdetl _cast = (Xfifbankdetl) _other;
		if (journalno == null ? _cast.journalno != journalno : !journalno.equals( _cast.journalno )) {
			return false;
		}
		
		if (txndate == null ? _cast.txndate != txndate : !txndate.equals( _cast.txndate )) {
			return false;
		}
		
		if (txntype == null ? _cast.txntype != txntype : !txntype.equals( _cast.txntype )) {
			return false;
		}
		
		if (totalcount == null ? _cast.totalcount != totalcount : !totalcount.equals( _cast.totalcount )) {
			return false;
		}
		
		if (currcount == null ? _cast.currcount != currcount : !currcount.equals( _cast.currcount )) {
			return false;
		}
		
		if (multiflag == null ? _cast.multiflag != multiflag : !multiflag.equals( _cast.multiflag )) {
			return false;
		}
		
		if (transferact == null ? _cast.transferact != transferact : !transferact.equals( _cast.transferact )) {
			return false;
		}
		
		if (totalamt == null ? _cast.totalamt != totalamt : !totalamt.equals( _cast.totalamt )) {
			return false;
		}
		
		if (failamt == null ? _cast.failamt != failamt : !failamt.equals( _cast.failamt )) {
			return false;
		}
		
		if (failcount == null ? _cast.failcount != failcount : !failcount.equals( _cast.failcount )) {
			return false;
		}
		
		if (usage == null ? _cast.usage != usage : !usage.equals( _cast.usage )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		if (remark1 == null ? _cast.remark1 != remark1 : !remark1.equals( _cast.remark1 )) {
			return false;
		}
		
		if (remark2 == null ? _cast.remark2 != remark2 : !remark2.equals( _cast.remark2 )) {
			return false;
		}
		
		if (startdate == null ? _cast.startdate != startdate : !startdate.equals( _cast.startdate )) {
			return false;
		}
		
		if (status == null ? _cast.status != status : !status.equals( _cast.status )) {
			return false;
		}
		
		if (bankid == null ? _cast.bankid != bankid : !bankid.equals( _cast.bankid )) {
			return false;
		}
		
		if (systemtype == null ? _cast.systemtype != systemtype : !systemtype.equals( _cast.systemtype )) {
			return false;
		}
		
		if (operatorid == null ? _cast.operatorid != operatorid : !operatorid.equals( _cast.operatorid )) {
			return false;
		}
		
		if (operatedate == null ? _cast.operatedate != operatedate : !operatedate.equals( _cast.operatedate )) {
			return false;
		}
		
		if (checkerid == null ? _cast.checkerid != checkerid : !checkerid.equals( _cast.checkerid )) {
			return false;
		}
		
		if (checkdate == null ? _cast.checkdate != checkdate : !checkdate.equals( _cast.checkdate )) {
			return false;
		}
		
		if (creatorid == null ? _cast.creatorid != creatorid : !creatorid.equals( _cast.creatorid )) {
			return false;
		}
		
		if (createdate == null ? _cast.createdate != createdate : !createdate.equals( _cast.createdate )) {
			return false;
		}
		
		if (createform == null ? _cast.createform != createform : !createform.equals( _cast.createform )) {
			return false;
		}
		
		if (updatorid == null ? _cast.updatorid != updatorid : !updatorid.equals( _cast.updatorid )) {
			return false;
		}
		
		if (updatedate == null ? _cast.updatedate != updatedate : !updatedate.equals( _cast.updatedate )) {
			return false;
		}
		
		if (updateform == null ? _cast.updateform != updateform : !updateform.equals( _cast.updateform )) {
			return false;
		}
		
		if (bizseqno == null ? _cast.bizseqno != bizseqno : !bizseqno.equals( _cast.bizseqno )) {
			return false;
		}
		
		if (data == null ? _cast.data != data : !data.equals( _cast.data )) {
			return false;
		}
		
		if (log == null ? _cast.log != log : !log.equals( _cast.log )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (journalno != null) {
			_hashCode = 29 * _hashCode + journalno.hashCode();
		}
		
		if (txndate != null) {
			_hashCode = 29 * _hashCode + txndate.hashCode();
		}
		
		if (txntype != null) {
			_hashCode = 29 * _hashCode + txntype.hashCode();
		}
		
		if (totalcount != null) {
			_hashCode = 29 * _hashCode + totalcount.hashCode();
		}
		
		if (currcount != null) {
			_hashCode = 29 * _hashCode + currcount.hashCode();
		}
		
		if (multiflag != null) {
			_hashCode = 29 * _hashCode + multiflag.hashCode();
		}
		
		if (transferact != null) {
			_hashCode = 29 * _hashCode + transferact.hashCode();
		}
		
		if (totalamt != null) {
			_hashCode = 29 * _hashCode + totalamt.hashCode();
		}
		
		if (failamt != null) {
			_hashCode = 29 * _hashCode + failamt.hashCode();
		}
		
		if (failcount != null) {
			_hashCode = 29 * _hashCode + failcount.hashCode();
		}
		
		if (usage != null) {
			_hashCode = 29 * _hashCode + usage.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		if (remark1 != null) {
			_hashCode = 29 * _hashCode + remark1.hashCode();
		}
		
		if (remark2 != null) {
			_hashCode = 29 * _hashCode + remark2.hashCode();
		}
		
		if (startdate != null) {
			_hashCode = 29 * _hashCode + startdate.hashCode();
		}
		
		if (status != null) {
			_hashCode = 29 * _hashCode + status.hashCode();
		}
		
		if (bankid != null) {
			_hashCode = 29 * _hashCode + bankid.hashCode();
		}
		
		if (systemtype != null) {
			_hashCode = 29 * _hashCode + systemtype.hashCode();
		}
		
		if (operatorid != null) {
			_hashCode = 29 * _hashCode + operatorid.hashCode();
		}
		
		if (operatedate != null) {
			_hashCode = 29 * _hashCode + operatedate.hashCode();
		}
		
		if (checkerid != null) {
			_hashCode = 29 * _hashCode + checkerid.hashCode();
		}
		
		if (checkdate != null) {
			_hashCode = 29 * _hashCode + checkdate.hashCode();
		}
		
		if (creatorid != null) {
			_hashCode = 29 * _hashCode + creatorid.hashCode();
		}
		
		if (createdate != null) {
			_hashCode = 29 * _hashCode + createdate.hashCode();
		}
		
		if (createform != null) {
			_hashCode = 29 * _hashCode + createform.hashCode();
		}
		
		if (updatorid != null) {
			_hashCode = 29 * _hashCode + updatorid.hashCode();
		}
		
		if (updatedate != null) {
			_hashCode = 29 * _hashCode + updatedate.hashCode();
		}
		
		if (updateform != null) {
			_hashCode = 29 * _hashCode + updateform.hashCode();
		}
		
		if (bizseqno != null) {
			_hashCode = 29 * _hashCode + bizseqno.hashCode();
		}
		
		if (data != null) {
			_hashCode = 29 * _hashCode + data.hashCode();
		}
		
		if (log != null) {
			_hashCode = 29 * _hashCode + log.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return XfifbankdetlPk
	 */
	public XfifbankdetlPk createPk()
	{
		return new XfifbankdetlPk(journalno);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "zt.cms.xf.common.dto.Xfifbankdetl: " );
		ret.append( "journalno=" + journalno );
		ret.append( ", txndate=" + txndate );
		ret.append( ", txntype=" + txntype );
		ret.append( ", totalcount=" + totalcount );
		ret.append( ", currcount=" + currcount );
		ret.append( ", multiflag=" + multiflag );
		ret.append( ", transferact=" + transferact );
		ret.append( ", totalamt=" + totalamt );
		ret.append( ", failamt=" + failamt );
		ret.append( ", failcount=" + failcount );
		ret.append( ", usage=" + usage );
		ret.append( ", remark=" + remark );
		ret.append( ", remark1=" + remark1 );
		ret.append( ", remark2=" + remark2 );
		ret.append( ", startdate=" + startdate );
		ret.append( ", status=" + status );
		ret.append( ", bankid=" + bankid );
		ret.append( ", systemtype=" + systemtype );
		ret.append( ", operatorid=" + operatorid );
		ret.append( ", operatedate=" + operatedate );
		ret.append( ", checkerid=" + checkerid );
		ret.append( ", checkdate=" + checkdate );
		ret.append( ", creatorid=" + creatorid );
		ret.append( ", createdate=" + createdate );
		ret.append( ", createform=" + createform );
		ret.append( ", updatorid=" + updatorid );
		ret.append( ", updatedate=" + updatedate );
		ret.append( ", updateform=" + updateform );
		ret.append( ", bizseqno=" + bizseqno );
		ret.append( ", data=" + data );
		ret.append( ", log=" + log );
		return ret.toString();
	}

}
