/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FDCutpayDetlStatusUpdateParam implements Serializable
{
	protected java.lang.String billstatusresult;

	protected java.lang.String billstatuscondition;

	/**
	 * Method 'FDCutpayDetlStatusUpdateParam'
	 * 
	 */
	public FDCutpayDetlStatusUpdateParam()
	{
	}

	/**
	 * Method 'getBillstatusresult'
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBillstatusresult()
	{
		return billstatusresult;
	}

	/**
	 * Method 'setBillstatusresult'
	 * 
	 * @param billstatusresult
	 */
	public void setBillstatusresult(java.lang.String billstatusresult)
	{
		this.billstatusresult = billstatusresult;
	}

	/**
	 * Method 'getBillstatuscondition'
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBillstatuscondition()
	{
		return billstatuscondition;
	}

	/**
	 * Method 'setBillstatuscondition'
	 * 
	 * @param billstatuscondition
	 */
	public void setBillstatuscondition(java.lang.String billstatuscondition)
	{
		this.billstatuscondition = billstatuscondition;
	}

}
