/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import zt.cms.xf.common.dao.*;
import zt.cms.xf.common.factory.*;
import zt.cms.xf.common.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.math.BigDecimal;
import java.util.Date;

public class Xfvcutpaydetl implements Serializable
{
	/** 
	 * This attribute maps to the column JOURNALNO in the XFVCUTPAYDETL table.
	 */
	protected String journalno;

	/** 
	 * This attribute maps to the column CONTRACTNO in the XFVCUTPAYDETL table.
	 */
	protected String contractno;

	/** 
	 * This attribute maps to the column POANO in the XFVCUTPAYDETL table.
	 */
	protected BigDecimal poano;

	/** 
	 * This attribute maps to the column BILLSTATUS in the XFVCUTPAYDETL table.
	 */
	protected String billstatus;

	/** 
	 * This attribute maps to the column RECVBANKID in the XFVCUTPAYDETL table.
	 */
	protected String recvbankid;

	/** 
	 * This attribute maps to the column RECVACT in the XFVCUTPAYDETL table.
	 */
	protected String recvact;

	/** 
	 * This attribute maps to the column PAYBACKACT in the XFVCUTPAYDETL table.
	 */
	protected String paybackact;

	/** 
	 * This attribute maps to the column PAYBACKBANKID in the XFVCUTPAYDETL table.
	 */
	protected String paybackbankid;

	/** 
	 * This attribute maps to the column PAYBACKDATE in the XFVCUTPAYDETL table.
	 */
	protected Date paybackdate;

	/** 
	 * This attribute maps to the column PAIDUPAMT in the XFVCUTPAYDETL table.
	 */
	protected BigDecimal paidupamt;

	/** 
	 * This attribute maps to the column APPNO in the XFVCUTPAYDETL table.
	 */
	protected String appno;

	/** 
	 * This attribute maps to the column PARTNERNAME in the XFVCUTPAYDETL table.
	 */
	protected String partnername;

	/** 
	 * This attribute maps to the column CLIENTNAME in the XFVCUTPAYDETL table.
	 */
	protected String clientname;

	/** 
	 * This attribute maps to the column PAYBACKAMT in the XFVCUTPAYDETL table.
	 */
	protected BigDecimal paybackamt;

	/** 
	 * This attribute maps to the column PARTNERBANKNAME in the XFVCUTPAYDETL table.
	 */
	protected String partnerbankname;

	/** 
	 * This attribute maps to the column PAYBACKBANKNAME in the XFVCUTPAYDETL table.
	 */
	protected String paybackbankname;

	/**
	 * Method 'Xfvcutpaydetl'
	 * 
	 */
	public Xfvcutpaydetl()
	{
	}

	/**
	 * Method 'getJournalno'
	 * 
	 * @return String
	 */
	public String getJournalno()
	{
		return journalno;
	}

	/**
	 * Method 'setJournalno'
	 * 
	 * @param journalno
	 */
	public void setJournalno(String journalno)
	{
		this.journalno = journalno;
	}

	/**
	 * Method 'getContractno'
	 * 
	 * @return String
	 */
	public String getContractno()
	{
		return contractno;
	}

	/**
	 * Method 'setContractno'
	 * 
	 * @param contractno
	 */
	public void setContractno(String contractno)
	{
		this.contractno = contractno;
	}

	/**
	 * Method 'getPoano'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getPoano()
	{
		return poano;
	}

	/**
	 * Method 'setPoano'
	 * 
	 * @param poano
	 */
	public void setPoano(BigDecimal poano)
	{
		this.poano = poano;
	}

	/**
	 * Method 'getBillstatus'
	 * 
	 * @return String
	 */
	public String getBillstatus()
	{
		return billstatus;
	}

	/**
	 * Method 'setBillstatus'
	 * 
	 * @param billstatus
	 */
	public void setBillstatus(String billstatus)
	{
		this.billstatus = billstatus;
	}

	/**
	 * Method 'getRecvbankid'
	 * 
	 * @return String
	 */
	public String getRecvbankid()
	{
		return recvbankid;
	}

	/**
	 * Method 'setRecvbankid'
	 * 
	 * @param recvbankid
	 */
	public void setRecvbankid(String recvbankid)
	{
		this.recvbankid = recvbankid;
	}

	/**
	 * Method 'getRecvact'
	 * 
	 * @return String
	 */
	public String getRecvact()
	{
		return recvact;
	}

	/**
	 * Method 'setRecvact'
	 * 
	 * @param recvact
	 */
	public void setRecvact(String recvact)
	{
		this.recvact = recvact;
	}

	/**
	 * Method 'getPaybackact'
	 * 
	 * @return String
	 */
	public String getPaybackact()
	{
		return paybackact;
	}

	/**
	 * Method 'setPaybackact'
	 * 
	 * @param paybackact
	 */
	public void setPaybackact(String paybackact)
	{
		this.paybackact = paybackact;
	}

	/**
	 * Method 'getPaybackbankid'
	 * 
	 * @return String
	 */
	public String getPaybackbankid()
	{
		return paybackbankid;
	}

	/**
	 * Method 'setPaybackbankid'
	 * 
	 * @param paybackbankid
	 */
	public void setPaybackbankid(String paybackbankid)
	{
		this.paybackbankid = paybackbankid;
	}

	/**
	 * Method 'getPaybackdate'
	 * 
	 * @return Date
	 */
	public Date getPaybackdate()
	{
		return paybackdate;
	}

	/**
	 * Method 'setPaybackdate'
	 * 
	 * @param paybackdate
	 */
	public void setPaybackdate(Date paybackdate)
	{
		this.paybackdate = paybackdate;
	}

	/**
	 * Method 'getPaidupamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getPaidupamt()
	{
		return paidupamt;
	}

	/**
	 * Method 'setPaidupamt'
	 * 
	 * @param paidupamt
	 */
	public void setPaidupamt(BigDecimal paidupamt)
	{
		this.paidupamt = paidupamt;
	}

	/**
	 * Method 'getAppno'
	 * 
	 * @return String
	 */
	public String getAppno()
	{
		return appno;
	}

	/**
	 * Method 'setAppno'
	 * 
	 * @param appno
	 */
	public void setAppno(String appno)
	{
		this.appno = appno;
	}

	/**
	 * Method 'getPartnername'
	 * 
	 * @return String
	 */
	public String getPartnername()
	{
		return partnername;
	}

	/**
	 * Method 'setPartnername'
	 * 
	 * @param partnername
	 */
	public void setPartnername(String partnername)
	{
		this.partnername = partnername;
	}

	/**
	 * Method 'getClientname'
	 * 
	 * @return String
	 */
	public String getClientname()
	{
		return clientname;
	}

	/**
	 * Method 'setClientname'
	 * 
	 * @param clientname
	 */
	public void setClientname(String clientname)
	{
		this.clientname = clientname;
	}

	/**
	 * Method 'getPaybackamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getPaybackamt()
	{
		return paybackamt;
	}

	/**
	 * Method 'setPaybackamt'
	 * 
	 * @param paybackamt
	 */
	public void setPaybackamt(BigDecimal paybackamt)
	{
		this.paybackamt = paybackamt;
	}

	/**
	 * Method 'getPartnerbankname'
	 * 
	 * @return String
	 */
	public String getPartnerbankname()
	{
		return partnerbankname;
	}

	/**
	 * Method 'setPartnerbankname'
	 * 
	 * @param partnerbankname
	 */
	public void setPartnerbankname(String partnerbankname)
	{
		this.partnerbankname = partnerbankname;
	}

	/**
	 * Method 'getPaybackbankname'
	 * 
	 * @return String
	 */
	public String getPaybackbankname()
	{
		return paybackbankname;
	}

	/**
	 * Method 'setPaybackbankname'
	 * 
	 * @param paybackbankname
	 */
	public void setPaybackbankname(String paybackbankname)
	{
		this.paybackbankname = paybackbankname;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Xfvcutpaydetl)) {
			return false;
		}
		
		final Xfvcutpaydetl _cast = (Xfvcutpaydetl) _other;
		if (journalno == null ? _cast.journalno != journalno : !journalno.equals( _cast.journalno )) {
			return false;
		}
		
		if (contractno == null ? _cast.contractno != contractno : !contractno.equals( _cast.contractno )) {
			return false;
		}
		
		if (poano == null ? _cast.poano != poano : !poano.equals( _cast.poano )) {
			return false;
		}
		
		if (billstatus == null ? _cast.billstatus != billstatus : !billstatus.equals( _cast.billstatus )) {
			return false;
		}
		
		if (recvbankid == null ? _cast.recvbankid != recvbankid : !recvbankid.equals( _cast.recvbankid )) {
			return false;
		}
		
		if (recvact == null ? _cast.recvact != recvact : !recvact.equals( _cast.recvact )) {
			return false;
		}
		
		if (paybackact == null ? _cast.paybackact != paybackact : !paybackact.equals( _cast.paybackact )) {
			return false;
		}
		
		if (paybackbankid == null ? _cast.paybackbankid != paybackbankid : !paybackbankid.equals( _cast.paybackbankid )) {
			return false;
		}
		
		if (paybackdate == null ? _cast.paybackdate != paybackdate : !paybackdate.equals( _cast.paybackdate )) {
			return false;
		}
		
		if (paidupamt == null ? _cast.paidupamt != paidupamt : !paidupamt.equals( _cast.paidupamt )) {
			return false;
		}
		
		if (appno == null ? _cast.appno != appno : !appno.equals( _cast.appno )) {
			return false;
		}
		
		if (partnername == null ? _cast.partnername != partnername : !partnername.equals( _cast.partnername )) {
			return false;
		}
		
		if (clientname == null ? _cast.clientname != clientname : !clientname.equals( _cast.clientname )) {
			return false;
		}
		
		if (paybackamt == null ? _cast.paybackamt != paybackamt : !paybackamt.equals( _cast.paybackamt )) {
			return false;
		}
		
		if (partnerbankname == null ? _cast.partnerbankname != partnerbankname : !partnerbankname.equals( _cast.partnerbankname )) {
			return false;
		}
		
		if (paybackbankname == null ? _cast.paybackbankname != paybackbankname : !paybackbankname.equals( _cast.paybackbankname )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (journalno != null) {
			_hashCode = 29 * _hashCode + journalno.hashCode();
		}
		
		if (contractno != null) {
			_hashCode = 29 * _hashCode + contractno.hashCode();
		}
		
		if (poano != null) {
			_hashCode = 29 * _hashCode + poano.hashCode();
		}
		
		if (billstatus != null) {
			_hashCode = 29 * _hashCode + billstatus.hashCode();
		}
		
		if (recvbankid != null) {
			_hashCode = 29 * _hashCode + recvbankid.hashCode();
		}
		
		if (recvact != null) {
			_hashCode = 29 * _hashCode + recvact.hashCode();
		}
		
		if (paybackact != null) {
			_hashCode = 29 * _hashCode + paybackact.hashCode();
		}
		
		if (paybackbankid != null) {
			_hashCode = 29 * _hashCode + paybackbankid.hashCode();
		}
		
		if (paybackdate != null) {
			_hashCode = 29 * _hashCode + paybackdate.hashCode();
		}
		
		if (paidupamt != null) {
			_hashCode = 29 * _hashCode + paidupamt.hashCode();
		}
		
		if (appno != null) {
			_hashCode = 29 * _hashCode + appno.hashCode();
		}
		
		if (partnername != null) {
			_hashCode = 29 * _hashCode + partnername.hashCode();
		}
		
		if (clientname != null) {
			_hashCode = 29 * _hashCode + clientname.hashCode();
		}
		
		if (paybackamt != null) {
			_hashCode = 29 * _hashCode + paybackamt.hashCode();
		}
		
		if (partnerbankname != null) {
			_hashCode = 29 * _hashCode + partnerbankname.hashCode();
		}
		
		if (paybackbankname != null) {
			_hashCode = 29 * _hashCode + paybackbankname.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "zt.cms.xf.common.dto.Xfvcutpaydetl: " );
		ret.append( "journalno=" + journalno );
		ret.append( ", contractno=" + contractno );
		ret.append( ", poano=" + poano );
		ret.append( ", billstatus=" + billstatus );
		ret.append( ", recvbankid=" + recvbankid );
		ret.append( ", recvact=" + recvact );
		ret.append( ", paybackact=" + paybackact );
		ret.append( ", paybackbankid=" + paybackbankid );
		ret.append( ", paybackdate=" + paybackdate );
		ret.append( ", paidupamt=" + paidupamt );
		ret.append( ", appno=" + appno );
		ret.append( ", partnername=" + partnername );
		ret.append( ", clientname=" + clientname );
		ret.append( ", paybackamt=" + paybackamt );
		ret.append( ", partnerbankname=" + partnerbankname );
		ret.append( ", paybackbankname=" + paybackbankname );
		return ret.toString();
	}

}
