/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the XFACTNOINFO table.
 */
public class XfactnoinfoPk implements Serializable
{
	protected String appactno;

	/** 
	 * Sets the value of appactno
	 */
	public void setAppactno(String appactno)
	{
		this.appactno = appactno;
	}

	/** 
	 * Gets the value of appactno
	 */
	public String getAppactno()
	{
		return appactno;
	}

	/**
	 * Method 'XfactnoinfoPk'
	 * 
	 */
	public XfactnoinfoPk()
	{
	}

	/**
	 * Method 'XfactnoinfoPk'
	 * 
	 * @param appactno
	 */
	public XfactnoinfoPk(final String appactno)
	{
		this.appactno = appactno;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof XfactnoinfoPk)) {
			return false;
		}
		
		final XfactnoinfoPk _cast = (XfactnoinfoPk) _other;
		if (appactno == null ? _cast.appactno != appactno : !appactno.equals( _cast.appactno )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (appactno != null) {
			_hashCode = 29 * _hashCode + appactno.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "zt.cms.xf.common.dto.XfactnoinfoPk: " );
		ret.append( "appactno=" + appactno );
		return ret.toString();
	}

}
