/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import zt.cms.xf.common.dao.*;
import zt.cms.xf.common.factory.*;
import zt.cms.xf.common.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;
import java.math.BigDecimal;

public class Xfcontract implements Serializable
{
	/** 
	 * This attribute maps to the column APPNO in the XFCONTRACT table.
	 */
	protected String appno;

	/** 
	 * This attribute maps to the column CONTRACTNO in the XFCONTRACT table.
	 */
	protected String contractno;

	/** 
	 * This attribute maps to the column APPTYPE in the XFCONTRACT table.
	 */
	protected String apptype;

	/** 
	 * This attribute maps to the column INTERESTTYPE in the XFCONTRACT table.
	 */
	protected String interesttype;

	/** 
	 * This attribute maps to the column STARTDATE in the XFCONTRACT table.
	 */
	protected Date startdate;

	/** 
	 * This attribute maps to the column PLACE in the XFCONTRACT table.
	 */
	protected String place;

	/** 
	 * This attribute maps to the column CONTRACTTYPE in the XFCONTRACT table.
	 */
	protected String contracttype;

	/** 
	 * This attribute maps to the column CSTATUS in the XFCONTRACT table.
	 */
	protected String cstatus;

	/** 
	 * This attribute maps to the column DURATION in the XFCONTRACT table.
	 */
	protected BigDecimal duration;

	/** 
	 * This attribute maps to the column CURNO in the XFCONTRACT table.
	 */
	protected String curno;

	/** 
	 * This attribute maps to the column CONTRACTAMT in the XFCONTRACT table.
	 */
	protected BigDecimal contractamt;

	/** 
	 * This attribute maps to the column PRINCIPALAMT in the XFCONTRACT table.
	 */
	protected BigDecimal principalamt;

	/** 
	 * This attribute maps to the column SERVICECHARGE in the XFCONTRACT table.
	 */
	protected BigDecimal servicecharge;

	/** 
	 * This attribute maps to the column LATEFEERATE in the XFCONTRACT table.
	 */
	protected BigDecimal latefeerate;

	/** 
	 * This attribute maps to the column BREACHFEERATE in the XFCONTRACT table.
	 */
	protected BigDecimal breachfeerate;

	/** 
	 * This attribute maps to the column MANAGERFEERATE in the XFCONTRACT table.
	 */
	protected BigDecimal managerfeerate;

	/** 
	 * This attribute maps to the column LOWESTLATEFEE in the XFCONTRACT table.
	 */
	protected BigDecimal lowestlatefee;

	/** 
	 * This attribute maps to the column PARTNERNAME in the XFCONTRACT table.
	 */
	protected String partnername;

	/** 
	 * This attribute maps to the column PARTNERACT in the XFCONTRACT table.
	 */
	protected String partneract;

	/** 
	 * This attribute maps to the column PARTNERBANKID in the XFCONTRACT table.
	 */
	protected String partnerbankid;

	/** 
	 * This attribute maps to the column PARTNERBANKNO in the XFCONTRACT table.
	 */
	protected String partnerbankno;

	/** 
	 * This attribute maps to the column PARTNERBANKNAME in the XFCONTRACT table.
	 */
	protected String partnerbankname;

	/** 
	 * This attribute maps to the column COMMNAME in the XFCONTRACT table.
	 */
	protected String commname;

	/** 
	 * This attribute maps to the column COMMTYPE in the XFCONTRACT table.
	 */
	protected String commtype;

	/** 
	 * This attribute maps to the column COMMNUM in the XFCONTRACT table.
	 */
	protected String commnum;

	/** 
	 * This attribute maps to the column CLIENTNO in the XFCONTRACT table.
	 */
	protected String clientno;

	/** 
	 * This attribute maps to the column CLIENTIDTYPE in the XFCONTRACT table.
	 */
	protected String clientidtype;

	/** 
	 * This attribute maps to the column CLIENTID in the XFCONTRACT table.
	 */
	protected String clientid;

	/** 
	 * This attribute maps to the column CLIENTNAME in the XFCONTRACT table.
	 */
	protected String clientname;

	/** 
	 * This attribute maps to the column PAYBACKACT in the XFCONTRACT table.
	 */
	protected String paybackact;

	/** 
	 * This attribute maps to the column PAYBACKACTNAME in the XFCONTRACT table.
	 */
	protected String paybackactname;

	/** 
	 * This attribute maps to the column PAYBACKBANKID in the XFCONTRACT table.
	 */
	protected String paybackbankid;

	/** 
	 * This attribute maps to the column PAYBACKBANKNO in the XFCONTRACT table.
	 */
	protected String paybackbankno;

	/** 
	 * This attribute maps to the column PAYBACKBANKNAME in the XFCONTRACT table.
	 */
	protected String paybackbankname;

	/** 
	 * This attribute maps to the column CLIENTACT in the XFCONTRACT table.
	 */
	protected String clientact;

	/** 
	 * This attribute maps to the column OPERATORID in the XFCONTRACT table.
	 */
	protected String operatorid;

	/** 
	 * This attribute maps to the column OPERATEDATE in the XFCONTRACT table.
	 */
	protected Date operatedate;

	/** 
	 * This attribute maps to the column CHECKERID in the XFCONTRACT table.
	 */
	protected String checkerid;

	/** 
	 * This attribute maps to the column CHECKDATE in the XFCONTRACT table.
	 */
	protected Date checkdate;

	/** 
	 * This attribute maps to the column REMARK in the XFCONTRACT table.
	 */
	protected String remark;

	/** 
	 * This attribute maps to the column CREATORID in the XFCONTRACT table.
	 */
	protected String creatorid;

	/** 
	 * This attribute maps to the column CREATEDATE in the XFCONTRACT table.
	 */
	protected Date createdate;

	/** 
	 * This attribute maps to the column CREATEFORM in the XFCONTRACT table.
	 */
	protected String createform;

	/** 
	 * This attribute maps to the column UPDATORID in the XFCONTRACT table.
	 */
	protected String updatorid;

	/** 
	 * This attribute maps to the column UPDATEDATE in the XFCONTRACT table.
	 */
	protected Date updatedate;

	/** 
	 * This attribute maps to the column UPDATEFORM in the XFCONTRACT table.
	 */
	protected String updateform;

	/** 
	 * This attribute maps to the column CUSTOMER_CODE in the XFCONTRACT table.
	 */
	protected String customerCode;

	/** 
	 * This attribute maps to the column SIGN_ACCOUNT_NO in the XFCONTRACT table.
	 */
	protected String signAccountNo;

	/** 
	 * This attribute maps to the column RECEIVEAMT in the XFCONTRACT table.
	 */
	protected BigDecimal receiveamt;

	/** 
	 * This attribute maps to the column WITHHOLDBANKNAME in the XFCONTRACT table.
	 */
	protected String withholdbankname;

	/** 
	 * This attribute maps to the column COMMAMT in the XFCONTRACT table.
	 */
	protected BigDecimal commamt;

	/** 
	 * This attribute maps to the column TERMINALCD in the XFCONTRACT table.
	 */
	protected String terminalcd;

	/** 
	 * This attribute maps to the column TERMINALDATE in the XFCONTRACT table.
	 */
	protected Date terminaldate;

	/** 
	 * This attribute maps to the column TERMINALREASON in the XFCONTRACT table.
	 */
	protected String terminalreason;

	/**
	 * Method 'Xfcontract'
	 * 
	 */
	public Xfcontract()
	{
	}

	/**
	 * Method 'getAppno'
	 * 
	 * @return String
	 */
	public String getAppno()
	{
		return appno;
	}

	/**
	 * Method 'setAppno'
	 * 
	 * @param appno
	 */
	public void setAppno(String appno)
	{
		this.appno = appno;
	}

	/**
	 * Method 'getContractno'
	 * 
	 * @return String
	 */
	public String getContractno()
	{
		return contractno;
	}

	/**
	 * Method 'setContractno'
	 * 
	 * @param contractno
	 */
	public void setContractno(String contractno)
	{
		this.contractno = contractno;
	}

	/**
	 * Method 'getApptype'
	 * 
	 * @return String
	 */
	public String getApptype()
	{
		return apptype;
	}

	/**
	 * Method 'setApptype'
	 * 
	 * @param apptype
	 */
	public void setApptype(String apptype)
	{
		this.apptype = apptype;
	}

	/**
	 * Method 'getInteresttype'
	 * 
	 * @return String
	 */
	public String getInteresttype()
	{
		return interesttype;
	}

	/**
	 * Method 'setInteresttype'
	 * 
	 * @param interesttype
	 */
	public void setInteresttype(String interesttype)
	{
		this.interesttype = interesttype;
	}

	/**
	 * Method 'getStartdate'
	 * 
	 * @return Date
	 */
	public Date getStartdate()
	{
		return startdate;
	}

	/**
	 * Method 'setStartdate'
	 * 
	 * @param startdate
	 */
	public void setStartdate(Date startdate)
	{
		this.startdate = startdate;
	}

	/**
	 * Method 'getPlace'
	 * 
	 * @return String
	 */
	public String getPlace()
	{
		return place;
	}

	/**
	 * Method 'setPlace'
	 * 
	 * @param place
	 */
	public void setPlace(String place)
	{
		this.place = place;
	}

	/**
	 * Method 'getContracttype'
	 * 
	 * @return String
	 */
	public String getContracttype()
	{
		return contracttype;
	}

	/**
	 * Method 'setContracttype'
	 * 
	 * @param contracttype
	 */
	public void setContracttype(String contracttype)
	{
		this.contracttype = contracttype;
	}

	/**
	 * Method 'getCstatus'
	 * 
	 * @return String
	 */
	public String getCstatus()
	{
		return cstatus;
	}

	/**
	 * Method 'setCstatus'
	 * 
	 * @param cstatus
	 */
	public void setCstatus(String cstatus)
	{
		this.cstatus = cstatus;
	}

	/**
	 * Method 'getDuration'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getDuration()
	{
		return duration;
	}

	/**
	 * Method 'setDuration'
	 * 
	 * @param duration
	 */
	public void setDuration(BigDecimal duration)
	{
		this.duration = duration;
	}

	/**
	 * Method 'getCurno'
	 * 
	 * @return String
	 */
	public String getCurno()
	{
		return curno;
	}

	/**
	 * Method 'setCurno'
	 * 
	 * @param curno
	 */
	public void setCurno(String curno)
	{
		this.curno = curno;
	}

	/**
	 * Method 'getContractamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getContractamt()
	{
		return contractamt;
	}

	/**
	 * Method 'setContractamt'
	 * 
	 * @param contractamt
	 */
	public void setContractamt(BigDecimal contractamt)
	{
		this.contractamt = contractamt;
	}

	/**
	 * Method 'getPrincipalamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getPrincipalamt()
	{
		return principalamt;
	}

	/**
	 * Method 'setPrincipalamt'
	 * 
	 * @param principalamt
	 */
	public void setPrincipalamt(BigDecimal principalamt)
	{
		this.principalamt = principalamt;
	}

	/**
	 * Method 'getServicecharge'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getServicecharge()
	{
		return servicecharge;
	}

	/**
	 * Method 'setServicecharge'
	 * 
	 * @param servicecharge
	 */
	public void setServicecharge(BigDecimal servicecharge)
	{
		this.servicecharge = servicecharge;
	}

	/**
	 * Method 'getLatefeerate'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getLatefeerate()
	{
		return latefeerate;
	}

	/**
	 * Method 'setLatefeerate'
	 * 
	 * @param latefeerate
	 */
	public void setLatefeerate(BigDecimal latefeerate)
	{
		this.latefeerate = latefeerate;
	}

	/**
	 * Method 'getBreachfeerate'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getBreachfeerate()
	{
		return breachfeerate;
	}

	/**
	 * Method 'setBreachfeerate'
	 * 
	 * @param breachfeerate
	 */
	public void setBreachfeerate(BigDecimal breachfeerate)
	{
		this.breachfeerate = breachfeerate;
	}

	/**
	 * Method 'getManagerfeerate'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getManagerfeerate()
	{
		return managerfeerate;
	}

	/**
	 * Method 'setManagerfeerate'
	 * 
	 * @param managerfeerate
	 */
	public void setManagerfeerate(BigDecimal managerfeerate)
	{
		this.managerfeerate = managerfeerate;
	}

	/**
	 * Method 'getLowestlatefee'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getLowestlatefee()
	{
		return lowestlatefee;
	}

	/**
	 * Method 'setLowestlatefee'
	 * 
	 * @param lowestlatefee
	 */
	public void setLowestlatefee(BigDecimal lowestlatefee)
	{
		this.lowestlatefee = lowestlatefee;
	}

	/**
	 * Method 'getPartnername'
	 * 
	 * @return String
	 */
	public String getPartnername()
	{
		return partnername;
	}

	/**
	 * Method 'setPartnername'
	 * 
	 * @param partnername
	 */
	public void setPartnername(String partnername)
	{
		this.partnername = partnername;
	}

	/**
	 * Method 'getPartneract'
	 * 
	 * @return String
	 */
	public String getPartneract()
	{
		return partneract;
	}

	/**
	 * Method 'setPartneract'
	 * 
	 * @param partneract
	 */
	public void setPartneract(String partneract)
	{
		this.partneract = partneract;
	}

	/**
	 * Method 'getPartnerbankid'
	 * 
	 * @return String
	 */
	public String getPartnerbankid()
	{
		return partnerbankid;
	}

	/**
	 * Method 'setPartnerbankid'
	 * 
	 * @param partnerbankid
	 */
	public void setPartnerbankid(String partnerbankid)
	{
		this.partnerbankid = partnerbankid;
	}

	/**
	 * Method 'getPartnerbankno'
	 * 
	 * @return String
	 */
	public String getPartnerbankno()
	{
		return partnerbankno;
	}

	/**
	 * Method 'setPartnerbankno'
	 * 
	 * @param partnerbankno
	 */
	public void setPartnerbankno(String partnerbankno)
	{
		this.partnerbankno = partnerbankno;
	}

	/**
	 * Method 'getPartnerbankname'
	 * 
	 * @return String
	 */
	public String getPartnerbankname()
	{
		return partnerbankname;
	}

	/**
	 * Method 'setPartnerbankname'
	 * 
	 * @param partnerbankname
	 */
	public void setPartnerbankname(String partnerbankname)
	{
		this.partnerbankname = partnerbankname;
	}

	/**
	 * Method 'getCommname'
	 * 
	 * @return String
	 */
	public String getCommname()
	{
		return commname;
	}

	/**
	 * Method 'setCommname'
	 * 
	 * @param commname
	 */
	public void setCommname(String commname)
	{
		this.commname = commname;
	}

	/**
	 * Method 'getCommtype'
	 * 
	 * @return String
	 */
	public String getCommtype()
	{
		return commtype;
	}

	/**
	 * Method 'setCommtype'
	 * 
	 * @param commtype
	 */
	public void setCommtype(String commtype)
	{
		this.commtype = commtype;
	}

	/**
	 * Method 'getCommnum'
	 * 
	 * @return String
	 */
	public String getCommnum()
	{
		return commnum;
	}

	/**
	 * Method 'setCommnum'
	 * 
	 * @param commnum
	 */
	public void setCommnum(String commnum)
	{
		this.commnum = commnum;
	}

	/**
	 * Method 'getClientno'
	 * 
	 * @return String
	 */
	public String getClientno()
	{
		return clientno;
	}

	/**
	 * Method 'setClientno'
	 * 
	 * @param clientno
	 */
	public void setClientno(String clientno)
	{
		this.clientno = clientno;
	}

	/**
	 * Method 'getClientidtype'
	 * 
	 * @return String
	 */
	public String getClientidtype()
	{
		return clientidtype;
	}

	/**
	 * Method 'setClientidtype'
	 * 
	 * @param clientidtype
	 */
	public void setClientidtype(String clientidtype)
	{
		this.clientidtype = clientidtype;
	}

	/**
	 * Method 'getClientid'
	 * 
	 * @return String
	 */
	public String getClientid()
	{
		return clientid;
	}

	/**
	 * Method 'setClientid'
	 * 
	 * @param clientid
	 */
	public void setClientid(String clientid)
	{
		this.clientid = clientid;
	}

	/**
	 * Method 'getClientname'
	 * 
	 * @return String
	 */
	public String getClientname()
	{
		return clientname;
	}

	/**
	 * Method 'setClientname'
	 * 
	 * @param clientname
	 */
	public void setClientname(String clientname)
	{
		this.clientname = clientname;
	}

	/**
	 * Method 'getPaybackact'
	 * 
	 * @return String
	 */
	public String getPaybackact()
	{
		return paybackact;
	}

	/**
	 * Method 'setPaybackact'
	 * 
	 * @param paybackact
	 */
	public void setPaybackact(String paybackact)
	{
		this.paybackact = paybackact;
	}

	/**
	 * Method 'getPaybackactname'
	 * 
	 * @return String
	 */
	public String getPaybackactname()
	{
		return paybackactname;
	}

	/**
	 * Method 'setPaybackactname'
	 * 
	 * @param paybackactname
	 */
	public void setPaybackactname(String paybackactname)
	{
		this.paybackactname = paybackactname;
	}

	/**
	 * Method 'getPaybackbankid'
	 * 
	 * @return String
	 */
	public String getPaybackbankid()
	{
		return paybackbankid;
	}

	/**
	 * Method 'setPaybackbankid'
	 * 
	 * @param paybackbankid
	 */
	public void setPaybackbankid(String paybackbankid)
	{
		this.paybackbankid = paybackbankid;
	}

	/**
	 * Method 'getPaybackbankno'
	 * 
	 * @return String
	 */
	public String getPaybackbankno()
	{
		return paybackbankno;
	}

	/**
	 * Method 'setPaybackbankno'
	 * 
	 * @param paybackbankno
	 */
	public void setPaybackbankno(String paybackbankno)
	{
		this.paybackbankno = paybackbankno;
	}

	/**
	 * Method 'getPaybackbankname'
	 * 
	 * @return String
	 */
	public String getPaybackbankname()
	{
		return paybackbankname;
	}

	/**
	 * Method 'setPaybackbankname'
	 * 
	 * @param paybackbankname
	 */
	public void setPaybackbankname(String paybackbankname)
	{
		this.paybackbankname = paybackbankname;
	}

	/**
	 * Method 'getClientact'
	 * 
	 * @return String
	 */
	public String getClientact()
	{
		return clientact;
	}

	/**
	 * Method 'setClientact'
	 * 
	 * @param clientact
	 */
	public void setClientact(String clientact)
	{
		this.clientact = clientact;
	}

	/**
	 * Method 'getOperatorid'
	 * 
	 * @return String
	 */
	public String getOperatorid()
	{
		return operatorid;
	}

	/**
	 * Method 'setOperatorid'
	 * 
	 * @param operatorid
	 */
	public void setOperatorid(String operatorid)
	{
		this.operatorid = operatorid;
	}

	/**
	 * Method 'getOperatedate'
	 * 
	 * @return Date
	 */
	public Date getOperatedate()
	{
		return operatedate;
	}

	/**
	 * Method 'setOperatedate'
	 * 
	 * @param operatedate
	 */
	public void setOperatedate(Date operatedate)
	{
		this.operatedate = operatedate;
	}

	/**
	 * Method 'getCheckerid'
	 * 
	 * @return String
	 */
	public String getCheckerid()
	{
		return checkerid;
	}

	/**
	 * Method 'setCheckerid'
	 * 
	 * @param checkerid
	 */
	public void setCheckerid(String checkerid)
	{
		this.checkerid = checkerid;
	}

	/**
	 * Method 'getCheckdate'
	 * 
	 * @return Date
	 */
	public Date getCheckdate()
	{
		return checkdate;
	}

	/**
	 * Method 'setCheckdate'
	 * 
	 * @param checkdate
	 */
	public void setCheckdate(Date checkdate)
	{
		this.checkdate = checkdate;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'getCreatorid'
	 * 
	 * @return String
	 */
	public String getCreatorid()
	{
		return creatorid;
	}

	/**
	 * Method 'setCreatorid'
	 * 
	 * @param creatorid
	 */
	public void setCreatorid(String creatorid)
	{
		this.creatorid = creatorid;
	}

	/**
	 * Method 'getCreatedate'
	 * 
	 * @return Date
	 */
	public Date getCreatedate()
	{
		return createdate;
	}

	/**
	 * Method 'setCreatedate'
	 * 
	 * @param createdate
	 */
	public void setCreatedate(Date createdate)
	{
		this.createdate = createdate;
	}

	/**
	 * Method 'getCreateform'
	 * 
	 * @return String
	 */
	public String getCreateform()
	{
		return createform;
	}

	/**
	 * Method 'setCreateform'
	 * 
	 * @param createform
	 */
	public void setCreateform(String createform)
	{
		this.createform = createform;
	}

	/**
	 * Method 'getUpdatorid'
	 * 
	 * @return String
	 */
	public String getUpdatorid()
	{
		return updatorid;
	}

	/**
	 * Method 'setUpdatorid'
	 * 
	 * @param updatorid
	 */
	public void setUpdatorid(String updatorid)
	{
		this.updatorid = updatorid;
	}

	/**
	 * Method 'getUpdatedate'
	 * 
	 * @return Date
	 */
	public Date getUpdatedate()
	{
		return updatedate;
	}

	/**
	 * Method 'setUpdatedate'
	 * 
	 * @param updatedate
	 */
	public void setUpdatedate(Date updatedate)
	{
		this.updatedate = updatedate;
	}

	/**
	 * Method 'getUpdateform'
	 * 
	 * @return String
	 */
	public String getUpdateform()
	{
		return updateform;
	}

	/**
	 * Method 'setUpdateform'
	 * 
	 * @param updateform
	 */
	public void setUpdateform(String updateform)
	{
		this.updateform = updateform;
	}

	/**
	 * Method 'getCustomerCode'
	 * 
	 * @return String
	 */
	public String getCustomerCode()
	{
		return customerCode;
	}

	/**
	 * Method 'setCustomerCode'
	 * 
	 * @param customerCode
	 */
	public void setCustomerCode(String customerCode)
	{
		this.customerCode = customerCode;
	}

	/**
	 * Method 'getSignAccountNo'
	 * 
	 * @return String
	 */
	public String getSignAccountNo()
	{
		return signAccountNo;
	}

	/**
	 * Method 'setSignAccountNo'
	 * 
	 * @param signAccountNo
	 */
	public void setSignAccountNo(String signAccountNo)
	{
		this.signAccountNo = signAccountNo;
	}

	/**
	 * Method 'getReceiveamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getReceiveamt()
	{
		return receiveamt;
	}

	/**
	 * Method 'setReceiveamt'
	 * 
	 * @param receiveamt
	 */
	public void setReceiveamt(BigDecimal receiveamt)
	{
		this.receiveamt = receiveamt;
	}

	/**
	 * Method 'getWithholdbankname'
	 * 
	 * @return String
	 */
	public String getWithholdbankname()
	{
		return withholdbankname;
	}

	/**
	 * Method 'setWithholdbankname'
	 * 
	 * @param withholdbankname
	 */
	public void setWithholdbankname(String withholdbankname)
	{
		this.withholdbankname = withholdbankname;
	}

	/**
	 * Method 'getCommamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getCommamt()
	{
		return commamt;
	}

	/**
	 * Method 'setCommamt'
	 * 
	 * @param commamt
	 */
	public void setCommamt(BigDecimal commamt)
	{
		this.commamt = commamt;
	}

	/**
	 * Method 'getTerminalcd'
	 * 
	 * @return String
	 */
	public String getTerminalcd()
	{
		return terminalcd;
	}

	/**
	 * Method 'setTerminalcd'
	 * 
	 * @param terminalcd
	 */
	public void setTerminalcd(String terminalcd)
	{
		this.terminalcd = terminalcd;
	}

	/**
	 * Method 'getTerminaldate'
	 * 
	 * @return Date
	 */
	public Date getTerminaldate()
	{
		return terminaldate;
	}

	/**
	 * Method 'setTerminaldate'
	 * 
	 * @param terminaldate
	 */
	public void setTerminaldate(Date terminaldate)
	{
		this.terminaldate = terminaldate;
	}

	/**
	 * Method 'getTerminalreason'
	 * 
	 * @return String
	 */
	public String getTerminalreason()
	{
		return terminalreason;
	}

	/**
	 * Method 'setTerminalreason'
	 * 
	 * @param terminalreason
	 */
	public void setTerminalreason(String terminalreason)
	{
		this.terminalreason = terminalreason;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Xfcontract)) {
			return false;
		}
		
		final Xfcontract _cast = (Xfcontract) _other;
		if (appno == null ? _cast.appno != appno : !appno.equals( _cast.appno )) {
			return false;
		}
		
		if (contractno == null ? _cast.contractno != contractno : !contractno.equals( _cast.contractno )) {
			return false;
		}
		
		if (apptype == null ? _cast.apptype != apptype : !apptype.equals( _cast.apptype )) {
			return false;
		}
		
		if (interesttype == null ? _cast.interesttype != interesttype : !interesttype.equals( _cast.interesttype )) {
			return false;
		}
		
		if (startdate == null ? _cast.startdate != startdate : !startdate.equals( _cast.startdate )) {
			return false;
		}
		
		if (place == null ? _cast.place != place : !place.equals( _cast.place )) {
			return false;
		}
		
		if (contracttype == null ? _cast.contracttype != contracttype : !contracttype.equals( _cast.contracttype )) {
			return false;
		}
		
		if (cstatus == null ? _cast.cstatus != cstatus : !cstatus.equals( _cast.cstatus )) {
			return false;
		}
		
		if (duration == null ? _cast.duration != duration : !duration.equals( _cast.duration )) {
			return false;
		}
		
		if (curno == null ? _cast.curno != curno : !curno.equals( _cast.curno )) {
			return false;
		}
		
		if (contractamt == null ? _cast.contractamt != contractamt : !contractamt.equals( _cast.contractamt )) {
			return false;
		}
		
		if (principalamt == null ? _cast.principalamt != principalamt : !principalamt.equals( _cast.principalamt )) {
			return false;
		}
		
		if (servicecharge == null ? _cast.servicecharge != servicecharge : !servicecharge.equals( _cast.servicecharge )) {
			return false;
		}
		
		if (latefeerate == null ? _cast.latefeerate != latefeerate : !latefeerate.equals( _cast.latefeerate )) {
			return false;
		}
		
		if (breachfeerate == null ? _cast.breachfeerate != breachfeerate : !breachfeerate.equals( _cast.breachfeerate )) {
			return false;
		}
		
		if (managerfeerate == null ? _cast.managerfeerate != managerfeerate : !managerfeerate.equals( _cast.managerfeerate )) {
			return false;
		}
		
		if (lowestlatefee == null ? _cast.lowestlatefee != lowestlatefee : !lowestlatefee.equals( _cast.lowestlatefee )) {
			return false;
		}
		
		if (partnername == null ? _cast.partnername != partnername : !partnername.equals( _cast.partnername )) {
			return false;
		}
		
		if (partneract == null ? _cast.partneract != partneract : !partneract.equals( _cast.partneract )) {
			return false;
		}
		
		if (partnerbankid == null ? _cast.partnerbankid != partnerbankid : !partnerbankid.equals( _cast.partnerbankid )) {
			return false;
		}
		
		if (partnerbankno == null ? _cast.partnerbankno != partnerbankno : !partnerbankno.equals( _cast.partnerbankno )) {
			return false;
		}
		
		if (partnerbankname == null ? _cast.partnerbankname != partnerbankname : !partnerbankname.equals( _cast.partnerbankname )) {
			return false;
		}
		
		if (commname == null ? _cast.commname != commname : !commname.equals( _cast.commname )) {
			return false;
		}
		
		if (commtype == null ? _cast.commtype != commtype : !commtype.equals( _cast.commtype )) {
			return false;
		}
		
		if (commnum == null ? _cast.commnum != commnum : !commnum.equals( _cast.commnum )) {
			return false;
		}
		
		if (clientno == null ? _cast.clientno != clientno : !clientno.equals( _cast.clientno )) {
			return false;
		}
		
		if (clientidtype == null ? _cast.clientidtype != clientidtype : !clientidtype.equals( _cast.clientidtype )) {
			return false;
		}
		
		if (clientid == null ? _cast.clientid != clientid : !clientid.equals( _cast.clientid )) {
			return false;
		}
		
		if (clientname == null ? _cast.clientname != clientname : !clientname.equals( _cast.clientname )) {
			return false;
		}
		
		if (paybackact == null ? _cast.paybackact != paybackact : !paybackact.equals( _cast.paybackact )) {
			return false;
		}
		
		if (paybackactname == null ? _cast.paybackactname != paybackactname : !paybackactname.equals( _cast.paybackactname )) {
			return false;
		}
		
		if (paybackbankid == null ? _cast.paybackbankid != paybackbankid : !paybackbankid.equals( _cast.paybackbankid )) {
			return false;
		}
		
		if (paybackbankno == null ? _cast.paybackbankno != paybackbankno : !paybackbankno.equals( _cast.paybackbankno )) {
			return false;
		}
		
		if (paybackbankname == null ? _cast.paybackbankname != paybackbankname : !paybackbankname.equals( _cast.paybackbankname )) {
			return false;
		}
		
		if (clientact == null ? _cast.clientact != clientact : !clientact.equals( _cast.clientact )) {
			return false;
		}
		
		if (operatorid == null ? _cast.operatorid != operatorid : !operatorid.equals( _cast.operatorid )) {
			return false;
		}
		
		if (operatedate == null ? _cast.operatedate != operatedate : !operatedate.equals( _cast.operatedate )) {
			return false;
		}
		
		if (checkerid == null ? _cast.checkerid != checkerid : !checkerid.equals( _cast.checkerid )) {
			return false;
		}
		
		if (checkdate == null ? _cast.checkdate != checkdate : !checkdate.equals( _cast.checkdate )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		if (creatorid == null ? _cast.creatorid != creatorid : !creatorid.equals( _cast.creatorid )) {
			return false;
		}
		
		if (createdate == null ? _cast.createdate != createdate : !createdate.equals( _cast.createdate )) {
			return false;
		}
		
		if (createform == null ? _cast.createform != createform : !createform.equals( _cast.createform )) {
			return false;
		}
		
		if (updatorid == null ? _cast.updatorid != updatorid : !updatorid.equals( _cast.updatorid )) {
			return false;
		}
		
		if (updatedate == null ? _cast.updatedate != updatedate : !updatedate.equals( _cast.updatedate )) {
			return false;
		}
		
		if (updateform == null ? _cast.updateform != updateform : !updateform.equals( _cast.updateform )) {
			return false;
		}
		
		if (customerCode == null ? _cast.customerCode != customerCode : !customerCode.equals( _cast.customerCode )) {
			return false;
		}
		
		if (signAccountNo == null ? _cast.signAccountNo != signAccountNo : !signAccountNo.equals( _cast.signAccountNo )) {
			return false;
		}
		
		if (receiveamt == null ? _cast.receiveamt != receiveamt : !receiveamt.equals( _cast.receiveamt )) {
			return false;
		}
		
		if (withholdbankname == null ? _cast.withholdbankname != withholdbankname : !withholdbankname.equals( _cast.withholdbankname )) {
			return false;
		}
		
		if (commamt == null ? _cast.commamt != commamt : !commamt.equals( _cast.commamt )) {
			return false;
		}
		
		if (terminalcd == null ? _cast.terminalcd != terminalcd : !terminalcd.equals( _cast.terminalcd )) {
			return false;
		}
		
		if (terminaldate == null ? _cast.terminaldate != terminaldate : !terminaldate.equals( _cast.terminaldate )) {
			return false;
		}
		
		if (terminalreason == null ? _cast.terminalreason != terminalreason : !terminalreason.equals( _cast.terminalreason )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (appno != null) {
			_hashCode = 29 * _hashCode + appno.hashCode();
		}
		
		if (contractno != null) {
			_hashCode = 29 * _hashCode + contractno.hashCode();
		}
		
		if (apptype != null) {
			_hashCode = 29 * _hashCode + apptype.hashCode();
		}
		
		if (interesttype != null) {
			_hashCode = 29 * _hashCode + interesttype.hashCode();
		}
		
		if (startdate != null) {
			_hashCode = 29 * _hashCode + startdate.hashCode();
		}
		
		if (place != null) {
			_hashCode = 29 * _hashCode + place.hashCode();
		}
		
		if (contracttype != null) {
			_hashCode = 29 * _hashCode + contracttype.hashCode();
		}
		
		if (cstatus != null) {
			_hashCode = 29 * _hashCode + cstatus.hashCode();
		}
		
		if (duration != null) {
			_hashCode = 29 * _hashCode + duration.hashCode();
		}
		
		if (curno != null) {
			_hashCode = 29 * _hashCode + curno.hashCode();
		}
		
		if (contractamt != null) {
			_hashCode = 29 * _hashCode + contractamt.hashCode();
		}
		
		if (principalamt != null) {
			_hashCode = 29 * _hashCode + principalamt.hashCode();
		}
		
		if (servicecharge != null) {
			_hashCode = 29 * _hashCode + servicecharge.hashCode();
		}
		
		if (latefeerate != null) {
			_hashCode = 29 * _hashCode + latefeerate.hashCode();
		}
		
		if (breachfeerate != null) {
			_hashCode = 29 * _hashCode + breachfeerate.hashCode();
		}
		
		if (managerfeerate != null) {
			_hashCode = 29 * _hashCode + managerfeerate.hashCode();
		}
		
		if (lowestlatefee != null) {
			_hashCode = 29 * _hashCode + lowestlatefee.hashCode();
		}
		
		if (partnername != null) {
			_hashCode = 29 * _hashCode + partnername.hashCode();
		}
		
		if (partneract != null) {
			_hashCode = 29 * _hashCode + partneract.hashCode();
		}
		
		if (partnerbankid != null) {
			_hashCode = 29 * _hashCode + partnerbankid.hashCode();
		}
		
		if (partnerbankno != null) {
			_hashCode = 29 * _hashCode + partnerbankno.hashCode();
		}
		
		if (partnerbankname != null) {
			_hashCode = 29 * _hashCode + partnerbankname.hashCode();
		}
		
		if (commname != null) {
			_hashCode = 29 * _hashCode + commname.hashCode();
		}
		
		if (commtype != null) {
			_hashCode = 29 * _hashCode + commtype.hashCode();
		}
		
		if (commnum != null) {
			_hashCode = 29 * _hashCode + commnum.hashCode();
		}
		
		if (clientno != null) {
			_hashCode = 29 * _hashCode + clientno.hashCode();
		}
		
		if (clientidtype != null) {
			_hashCode = 29 * _hashCode + clientidtype.hashCode();
		}
		
		if (clientid != null) {
			_hashCode = 29 * _hashCode + clientid.hashCode();
		}
		
		if (clientname != null) {
			_hashCode = 29 * _hashCode + clientname.hashCode();
		}
		
		if (paybackact != null) {
			_hashCode = 29 * _hashCode + paybackact.hashCode();
		}
		
		if (paybackactname != null) {
			_hashCode = 29 * _hashCode + paybackactname.hashCode();
		}
		
		if (paybackbankid != null) {
			_hashCode = 29 * _hashCode + paybackbankid.hashCode();
		}
		
		if (paybackbankno != null) {
			_hashCode = 29 * _hashCode + paybackbankno.hashCode();
		}
		
		if (paybackbankname != null) {
			_hashCode = 29 * _hashCode + paybackbankname.hashCode();
		}
		
		if (clientact != null) {
			_hashCode = 29 * _hashCode + clientact.hashCode();
		}
		
		if (operatorid != null) {
			_hashCode = 29 * _hashCode + operatorid.hashCode();
		}
		
		if (operatedate != null) {
			_hashCode = 29 * _hashCode + operatedate.hashCode();
		}
		
		if (checkerid != null) {
			_hashCode = 29 * _hashCode + checkerid.hashCode();
		}
		
		if (checkdate != null) {
			_hashCode = 29 * _hashCode + checkdate.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		if (creatorid != null) {
			_hashCode = 29 * _hashCode + creatorid.hashCode();
		}
		
		if (createdate != null) {
			_hashCode = 29 * _hashCode + createdate.hashCode();
		}
		
		if (createform != null) {
			_hashCode = 29 * _hashCode + createform.hashCode();
		}
		
		if (updatorid != null) {
			_hashCode = 29 * _hashCode + updatorid.hashCode();
		}
		
		if (updatedate != null) {
			_hashCode = 29 * _hashCode + updatedate.hashCode();
		}
		
		if (updateform != null) {
			_hashCode = 29 * _hashCode + updateform.hashCode();
		}
		
		if (customerCode != null) {
			_hashCode = 29 * _hashCode + customerCode.hashCode();
		}
		
		if (signAccountNo != null) {
			_hashCode = 29 * _hashCode + signAccountNo.hashCode();
		}
		
		if (receiveamt != null) {
			_hashCode = 29 * _hashCode + receiveamt.hashCode();
		}
		
		if (withholdbankname != null) {
			_hashCode = 29 * _hashCode + withholdbankname.hashCode();
		}
		
		if (commamt != null) {
			_hashCode = 29 * _hashCode + commamt.hashCode();
		}
		
		if (terminalcd != null) {
			_hashCode = 29 * _hashCode + terminalcd.hashCode();
		}
		
		if (terminaldate != null) {
			_hashCode = 29 * _hashCode + terminaldate.hashCode();
		}
		
		if (terminalreason != null) {
			_hashCode = 29 * _hashCode + terminalreason.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return XfcontractPk
	 */
	public XfcontractPk createPk()
	{
		return new XfcontractPk(contractno);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "zt.cms.xf.common.dto.Xfcontract: " );
		ret.append( "appno=" + appno );
		ret.append( ", contractno=" + contractno );
		ret.append( ", apptype=" + apptype );
		ret.append( ", interesttype=" + interesttype );
		ret.append( ", startdate=" + startdate );
		ret.append( ", place=" + place );
		ret.append( ", contracttype=" + contracttype );
		ret.append( ", cstatus=" + cstatus );
		ret.append( ", duration=" + duration );
		ret.append( ", curno=" + curno );
		ret.append( ", contractamt=" + contractamt );
		ret.append( ", principalamt=" + principalamt );
		ret.append( ", servicecharge=" + servicecharge );
		ret.append( ", latefeerate=" + latefeerate );
		ret.append( ", breachfeerate=" + breachfeerate );
		ret.append( ", managerfeerate=" + managerfeerate );
		ret.append( ", lowestlatefee=" + lowestlatefee );
		ret.append( ", partnername=" + partnername );
		ret.append( ", partneract=" + partneract );
		ret.append( ", partnerbankid=" + partnerbankid );
		ret.append( ", partnerbankno=" + partnerbankno );
		ret.append( ", partnerbankname=" + partnerbankname );
		ret.append( ", commname=" + commname );
		ret.append( ", commtype=" + commtype );
		ret.append( ", commnum=" + commnum );
		ret.append( ", clientno=" + clientno );
		ret.append( ", clientidtype=" + clientidtype );
		ret.append( ", clientid=" + clientid );
		ret.append( ", clientname=" + clientname );
		ret.append( ", paybackact=" + paybackact );
		ret.append( ", paybackactname=" + paybackactname );
		ret.append( ", paybackbankid=" + paybackbankid );
		ret.append( ", paybackbankno=" + paybackbankno );
		ret.append( ", paybackbankname=" + paybackbankname );
		ret.append( ", clientact=" + clientact );
		ret.append( ", operatorid=" + operatorid );
		ret.append( ", operatedate=" + operatedate );
		ret.append( ", checkerid=" + checkerid );
		ret.append( ", checkdate=" + checkdate );
		ret.append( ", remark=" + remark );
		ret.append( ", creatorid=" + creatorid );
		ret.append( ", createdate=" + createdate );
		ret.append( ", createform=" + createform );
		ret.append( ", updatorid=" + updatorid );
		ret.append( ", updatedate=" + updatedate );
		ret.append( ", updateform=" + updateform );
		ret.append( ", customerCode=" + customerCode );
		ret.append( ", signAccountNo=" + signAccountNo );
		ret.append( ", receiveamt=" + receiveamt );
		ret.append( ", withholdbankname=" + withholdbankname );
		ret.append( ", commamt=" + commamt );
		ret.append( ", terminalcd=" + terminalcd );
		ret.append( ", terminaldate=" + terminaldate );
		ret.append( ", terminalreason=" + terminalreason );
		return ret.toString();
	}

}
