/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import zt.cms.xf.common.dao.*;
import zt.cms.xf.common.factory.*;
import zt.cms.xf.common.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.math.BigDecimal;

public class Xfvappinfo implements Serializable
{
	/** 
	 * This attribute maps to the column APPNO in the XFVAPPINFO table.
	 */
	protected String appno;

	/** 
	 * This attribute maps to the column CLIENTID in the XFVAPPINFO table.
	 */
	protected String clientid;

	/** 
	 * This attribute maps to the column CLIENTIDTYPE in the XFVAPPINFO table.
	 */
	protected String clientidtype;

	/** 
	 * This attribute maps to the column CLIENTNAME in the XFVAPPINFO table.
	 */
	protected String clientname;

	/** 
	 * This attribute maps to the column APPTYPE in the XFVAPPINFO table.
	 */
	protected String apptype;

	/** 
	 * This attribute maps to the column STARTDATE in the XFVAPPINFO table.
	 */
	protected String startdate;

	/** 
	 * This attribute maps to the column CONTRACTAMT in the XFVAPPINFO table.
	 */
	protected BigDecimal contractamt;

	/** 
	 * This attribute maps to the column DURATION in the XFVAPPINFO table.
	 */
	protected String duration;

	/** 
	 * This attribute maps to the column SERVICECHARGE in the XFVAPPINFO table.
	 */
	protected BigDecimal servicecharge;

	/** 
	 * This attribute maps to the column PARTNERNAME in the XFVAPPINFO table.
	 */
	protected String partnername;

	/** 
	 * This attribute maps to the column PARTNERACT in the XFVAPPINFO table.
	 */
	protected String partneract;

	/** 
	 * This attribute maps to the column COMMNAME in the XFVAPPINFO table.
	 */
	protected String commname;

	/** 
	 * This attribute maps to the column COMMTYPE in the XFVAPPINFO table.
	 */
	protected String commtype;

	/** 
	 * This attribute maps to the column COMMNUM in the XFVAPPINFO table.
	 */
	protected String commnum;

	/** 
	 * This attribute maps to the column PAYBACKACT in the XFVAPPINFO table.
	 */
	protected String paybackact;

	/** 
	 * This attribute maps to the column PAYBACKBANKID in the XFVAPPINFO table.
	 */
	protected String paybackbankid;

	/** 
	 * This attribute maps to the column CUSTOMER_CODE in the XFVAPPINFO table.
	 */
	protected String customerCode;

	/** 
	 * This attribute maps to the column SIGN_ACCOUNT_NO in the XFVAPPINFO table.
	 */
	protected String signAccountNo;

	/** 
	 * This attribute maps to the column RECEIVEAMT in the XFVAPPINFO table.
	 */
	protected BigDecimal receiveamt;

	/** 
	 * This attribute maps to the column CLIENTNO in the XFVAPPINFO table.
	 */
	protected BigDecimal clientno;

	/** 
	 * This attribute maps to the column COMMAMT in the XFVAPPINFO table.
	 */
	protected BigDecimal commamt;

	/**
	 * Method 'Xfvappinfo'
	 * 
	 */
	public Xfvappinfo()
	{
	}

	/**
	 * Method 'getAppno'
	 * 
	 * @return String
	 */
	public String getAppno()
	{
		return appno;
	}

	/**
	 * Method 'setAppno'
	 * 
	 * @param appno
	 */
	public void setAppno(String appno)
	{
		this.appno = appno;
	}

	/**
	 * Method 'getClientid'
	 * 
	 * @return String
	 */
	public String getClientid()
	{
		return clientid;
	}

	/**
	 * Method 'setClientid'
	 * 
	 * @param clientid
	 */
	public void setClientid(String clientid)
	{
		this.clientid = clientid;
	}

	/**
	 * Method 'getClientidtype'
	 * 
	 * @return String
	 */
	public String getClientidtype()
	{
		return clientidtype;
	}

	/**
	 * Method 'setClientidtype'
	 * 
	 * @param clientidtype
	 */
	public void setClientidtype(String clientidtype)
	{
		this.clientidtype = clientidtype;
	}

	/**
	 * Method 'getClientname'
	 * 
	 * @return String
	 */
	public String getClientname()
	{
		return clientname;
	}

	/**
	 * Method 'setClientname'
	 * 
	 * @param clientname
	 */
	public void setClientname(String clientname)
	{
		this.clientname = clientname;
	}

	/**
	 * Method 'getApptype'
	 * 
	 * @return String
	 */
	public String getApptype()
	{
		return apptype;
	}

	/**
	 * Method 'setApptype'
	 * 
	 * @param apptype
	 */
	public void setApptype(String apptype)
	{
		this.apptype = apptype;
	}

	/**
	 * Method 'getStartdate'
	 * 
	 * @return String
	 */
	public String getStartdate()
	{
		return startdate;
	}

	/**
	 * Method 'setStartdate'
	 * 
	 * @param startdate
	 */
	public void setStartdate(String startdate)
	{
		this.startdate = startdate;
	}

	/**
	 * Method 'getContractamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getContractamt()
	{
		return contractamt;
	}

	/**
	 * Method 'setContractamt'
	 * 
	 * @param contractamt
	 */
	public void setContractamt(BigDecimal contractamt)
	{
		this.contractamt = contractamt;
	}

	/**
	 * Method 'getDuration'
	 * 
	 * @return String
	 */
	public String getDuration()
	{
		return duration;
	}

	/**
	 * Method 'setDuration'
	 * 
	 * @param duration
	 */
	public void setDuration(String duration)
	{
		this.duration = duration;
	}

	/**
	 * Method 'getServicecharge'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getServicecharge()
	{
		return servicecharge;
	}

	/**
	 * Method 'setServicecharge'
	 * 
	 * @param servicecharge
	 */
	public void setServicecharge(BigDecimal servicecharge)
	{
		this.servicecharge = servicecharge;
	}

	/**
	 * Method 'getPartnername'
	 * 
	 * @return String
	 */
	public String getPartnername()
	{
		return partnername;
	}

	/**
	 * Method 'setPartnername'
	 * 
	 * @param partnername
	 */
	public void setPartnername(String partnername)
	{
		this.partnername = partnername;
	}

	/**
	 * Method 'getPartneract'
	 * 
	 * @return String
	 */
	public String getPartneract()
	{
		return partneract;
	}

	/**
	 * Method 'setPartneract'
	 * 
	 * @param partneract
	 */
	public void setPartneract(String partneract)
	{
		this.partneract = partneract;
	}

	/**
	 * Method 'getCommname'
	 * 
	 * @return String
	 */
	public String getCommname()
	{
		return commname;
	}

	/**
	 * Method 'setCommname'
	 * 
	 * @param commname
	 */
	public void setCommname(String commname)
	{
		this.commname = commname;
	}

	/**
	 * Method 'getCommtype'
	 * 
	 * @return String
	 */
	public String getCommtype()
	{
		return commtype;
	}

	/**
	 * Method 'setCommtype'
	 * 
	 * @param commtype
	 */
	public void setCommtype(String commtype)
	{
		this.commtype = commtype;
	}

	/**
	 * Method 'getCommnum'
	 * 
	 * @return String
	 */
	public String getCommnum()
	{
		return commnum;
	}

	/**
	 * Method 'setCommnum'
	 * 
	 * @param commnum
	 */
	public void setCommnum(String commnum)
	{
		this.commnum = commnum;
	}

	/**
	 * Method 'getPaybackact'
	 * 
	 * @return String
	 */
	public String getPaybackact()
	{
		return paybackact;
	}

	/**
	 * Method 'setPaybackact'
	 * 
	 * @param paybackact
	 */
	public void setPaybackact(String paybackact)
	{
		this.paybackact = paybackact;
	}

	/**
	 * Method 'getPaybackbankid'
	 * 
	 * @return String
	 */
	public String getPaybackbankid()
	{
		return paybackbankid;
	}

	/**
	 * Method 'setPaybackbankid'
	 * 
	 * @param paybackbankid
	 */
	public void setPaybackbankid(String paybackbankid)
	{
		this.paybackbankid = paybackbankid;
	}

	/**
	 * Method 'getCustomerCode'
	 * 
	 * @return String
	 */
	public String getCustomerCode()
	{
		return customerCode;
	}

	/**
	 * Method 'setCustomerCode'
	 * 
	 * @param customerCode
	 */
	public void setCustomerCode(String customerCode)
	{
		this.customerCode = customerCode;
	}

	/**
	 * Method 'getSignAccountNo'
	 * 
	 * @return String
	 */
	public String getSignAccountNo()
	{
		return signAccountNo;
	}

	/**
	 * Method 'setSignAccountNo'
	 * 
	 * @param signAccountNo
	 */
	public void setSignAccountNo(String signAccountNo)
	{
		this.signAccountNo = signAccountNo;
	}

	/**
	 * Method 'getReceiveamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getReceiveamt()
	{
		return receiveamt;
	}

	/**
	 * Method 'setReceiveamt'
	 * 
	 * @param receiveamt
	 */
	public void setReceiveamt(BigDecimal receiveamt)
	{
		this.receiveamt = receiveamt;
	}

	/**
	 * Method 'getClientno'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getClientno()
	{
		return clientno;
	}

	/**
	 * Method 'setClientno'
	 * 
	 * @param clientno
	 */
	public void setClientno(BigDecimal clientno)
	{
		this.clientno = clientno;
	}

	/**
	 * Method 'getCommamt'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getCommamt()
	{
		return commamt;
	}

	/**
	 * Method 'setCommamt'
	 * 
	 * @param commamt
	 */
	public void setCommamt(BigDecimal commamt)
	{
		this.commamt = commamt;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Xfvappinfo)) {
			return false;
		}
		
		final Xfvappinfo _cast = (Xfvappinfo) _other;
		if (appno == null ? _cast.appno != appno : !appno.equals( _cast.appno )) {
			return false;
		}
		
		if (clientid == null ? _cast.clientid != clientid : !clientid.equals( _cast.clientid )) {
			return false;
		}
		
		if (clientidtype == null ? _cast.clientidtype != clientidtype : !clientidtype.equals( _cast.clientidtype )) {
			return false;
		}
		
		if (clientname == null ? _cast.clientname != clientname : !clientname.equals( _cast.clientname )) {
			return false;
		}
		
		if (apptype == null ? _cast.apptype != apptype : !apptype.equals( _cast.apptype )) {
			return false;
		}
		
		if (startdate == null ? _cast.startdate != startdate : !startdate.equals( _cast.startdate )) {
			return false;
		}
		
		if (contractamt == null ? _cast.contractamt != contractamt : !contractamt.equals( _cast.contractamt )) {
			return false;
		}
		
		if (duration == null ? _cast.duration != duration : !duration.equals( _cast.duration )) {
			return false;
		}
		
		if (servicecharge == null ? _cast.servicecharge != servicecharge : !servicecharge.equals( _cast.servicecharge )) {
			return false;
		}
		
		if (partnername == null ? _cast.partnername != partnername : !partnername.equals( _cast.partnername )) {
			return false;
		}
		
		if (partneract == null ? _cast.partneract != partneract : !partneract.equals( _cast.partneract )) {
			return false;
		}
		
		if (commname == null ? _cast.commname != commname : !commname.equals( _cast.commname )) {
			return false;
		}
		
		if (commtype == null ? _cast.commtype != commtype : !commtype.equals( _cast.commtype )) {
			return false;
		}
		
		if (commnum == null ? _cast.commnum != commnum : !commnum.equals( _cast.commnum )) {
			return false;
		}
		
		if (paybackact == null ? _cast.paybackact != paybackact : !paybackact.equals( _cast.paybackact )) {
			return false;
		}
		
		if (paybackbankid == null ? _cast.paybackbankid != paybackbankid : !paybackbankid.equals( _cast.paybackbankid )) {
			return false;
		}
		
		if (customerCode == null ? _cast.customerCode != customerCode : !customerCode.equals( _cast.customerCode )) {
			return false;
		}
		
		if (signAccountNo == null ? _cast.signAccountNo != signAccountNo : !signAccountNo.equals( _cast.signAccountNo )) {
			return false;
		}
		
		if (receiveamt == null ? _cast.receiveamt != receiveamt : !receiveamt.equals( _cast.receiveamt )) {
			return false;
		}
		
		if (clientno == null ? _cast.clientno != clientno : !clientno.equals( _cast.clientno )) {
			return false;
		}
		
		if (commamt == null ? _cast.commamt != commamt : !commamt.equals( _cast.commamt )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (appno != null) {
			_hashCode = 29 * _hashCode + appno.hashCode();
		}
		
		if (clientid != null) {
			_hashCode = 29 * _hashCode + clientid.hashCode();
		}
		
		if (clientidtype != null) {
			_hashCode = 29 * _hashCode + clientidtype.hashCode();
		}
		
		if (clientname != null) {
			_hashCode = 29 * _hashCode + clientname.hashCode();
		}
		
		if (apptype != null) {
			_hashCode = 29 * _hashCode + apptype.hashCode();
		}
		
		if (startdate != null) {
			_hashCode = 29 * _hashCode + startdate.hashCode();
		}
		
		if (contractamt != null) {
			_hashCode = 29 * _hashCode + contractamt.hashCode();
		}
		
		if (duration != null) {
			_hashCode = 29 * _hashCode + duration.hashCode();
		}
		
		if (servicecharge != null) {
			_hashCode = 29 * _hashCode + servicecharge.hashCode();
		}
		
		if (partnername != null) {
			_hashCode = 29 * _hashCode + partnername.hashCode();
		}
		
		if (partneract != null) {
			_hashCode = 29 * _hashCode + partneract.hashCode();
		}
		
		if (commname != null) {
			_hashCode = 29 * _hashCode + commname.hashCode();
		}
		
		if (commtype != null) {
			_hashCode = 29 * _hashCode + commtype.hashCode();
		}
		
		if (commnum != null) {
			_hashCode = 29 * _hashCode + commnum.hashCode();
		}
		
		if (paybackact != null) {
			_hashCode = 29 * _hashCode + paybackact.hashCode();
		}
		
		if (paybackbankid != null) {
			_hashCode = 29 * _hashCode + paybackbankid.hashCode();
		}
		
		if (customerCode != null) {
			_hashCode = 29 * _hashCode + customerCode.hashCode();
		}
		
		if (signAccountNo != null) {
			_hashCode = 29 * _hashCode + signAccountNo.hashCode();
		}
		
		if (receiveamt != null) {
			_hashCode = 29 * _hashCode + receiveamt.hashCode();
		}
		
		if (clientno != null) {
			_hashCode = 29 * _hashCode + clientno.hashCode();
		}
		
		if (commamt != null) {
			_hashCode = 29 * _hashCode + commamt.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "zt.cms.xf.common.dto.Xfvappinfo: " );
		ret.append( "appno=" + appno );
		ret.append( ", clientid=" + clientid );
		ret.append( ", clientidtype=" + clientidtype );
		ret.append( ", clientname=" + clientname );
		ret.append( ", apptype=" + apptype );
		ret.append( ", startdate=" + startdate );
		ret.append( ", contractamt=" + contractamt );
		ret.append( ", duration=" + duration );
		ret.append( ", servicecharge=" + servicecharge );
		ret.append( ", partnername=" + partnername );
		ret.append( ", partneract=" + partneract );
		ret.append( ", commname=" + commname );
		ret.append( ", commtype=" + commtype );
		ret.append( ", commnum=" + commnum );
		ret.append( ", paybackact=" + paybackact );
		ret.append( ", paybackbankid=" + paybackbankid );
		ret.append( ", customerCode=" + customerCode );
		ret.append( ", signAccountNo=" + signAccountNo );
		ret.append( ", receiveamt=" + receiveamt );
		ret.append( ", clientno=" + clientno );
		ret.append( ", commamt=" + commamt );
		return ret.toString();
	}

}
