/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dto;

import zt.cms.xf.common.dao.*;
import zt.cms.xf.common.factory.*;
import zt.cms.xf.common.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;
import java.math.BigDecimal;

public class Xfactnoinfo implements Serializable
{
	/** 
	 * This attribute maps to the column APPACTNO in the XFACTNOINFO table.
	 */
	protected String appactno;

	/** 
	 * This attribute maps to the column APPNO in the XFACTNOINFO table.
	 */
	protected String appno;

	/** 
	 * This attribute maps to the column STARTDATE in the XFACTNOINFO table.
	 */
	protected Date startdate;

	/** 
	 * This attribute maps to the column ENDDATE in the XFACTNOINFO table.
	 */
	protected Date enddate;

	/** 
	 * This attribute maps to the column ACTNOSTATUS in the XFACTNOINFO table.
	 */
	protected BigDecimal actnostatus;

	/** 
	 * This attribute maps to the column CREATORID in the XFACTNOINFO table.
	 */
	protected String creatorid;

	/** 
	 * This attribute maps to the column CREATEDATE in the XFACTNOINFO table.
	 */
	protected Date createdate;

	/** 
	 * This attribute maps to the column CREATEFORM in the XFACTNOINFO table.
	 */
	protected String createform;

	/** 
	 * This attribute maps to the column UPDATORID in the XFACTNOINFO table.
	 */
	protected String updatorid;

	/** 
	 * This attribute maps to the column UPDATEDATE in the XFACTNOINFO table.
	 */
	protected Date updatedate;

	/** 
	 * This attribute maps to the column UPDATEFORM in the XFACTNOINFO table.
	 */
	protected String updateform;

	/**
	 * Method 'Xfactnoinfo'
	 * 
	 */
	public Xfactnoinfo()
	{
	}

	/**
	 * Method 'getAppactno'
	 * 
	 * @return String
	 */
	public String getAppactno()
	{
		return appactno;
	}

	/**
	 * Method 'setAppactno'
	 * 
	 * @param appactno
	 */
	public void setAppactno(String appactno)
	{
		this.appactno = appactno;
	}

	/**
	 * Method 'getAppno'
	 * 
	 * @return String
	 */
	public String getAppno()
	{
		return appno;
	}

	/**
	 * Method 'setAppno'
	 * 
	 * @param appno
	 */
	public void setAppno(String appno)
	{
		this.appno = appno;
	}

	/**
	 * Method 'getStartdate'
	 * 
	 * @return Date
	 */
	public Date getStartdate()
	{
		return startdate;
	}

	/**
	 * Method 'setStartdate'
	 * 
	 * @param startdate
	 */
	public void setStartdate(Date startdate)
	{
		this.startdate = startdate;
	}

	/**
	 * Method 'getEnddate'
	 * 
	 * @return Date
	 */
	public Date getEnddate()
	{
		return enddate;
	}

	/**
	 * Method 'setEnddate'
	 * 
	 * @param enddate
	 */
	public void setEnddate(Date enddate)
	{
		this.enddate = enddate;
	}

	/**
	 * Method 'getActnostatus'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getActnostatus()
	{
		return actnostatus;
	}

	/**
	 * Method 'setActnostatus'
	 * 
	 * @param actnostatus
	 */
	public void setActnostatus(BigDecimal actnostatus)
	{
		this.actnostatus = actnostatus;
	}

	/**
	 * Method 'getCreatorid'
	 * 
	 * @return String
	 */
	public String getCreatorid()
	{
		return creatorid;
	}

	/**
	 * Method 'setCreatorid'
	 * 
	 * @param creatorid
	 */
	public void setCreatorid(String creatorid)
	{
		this.creatorid = creatorid;
	}

	/**
	 * Method 'getCreatedate'
	 * 
	 * @return Date
	 */
	public Date getCreatedate()
	{
		return createdate;
	}

	/**
	 * Method 'setCreatedate'
	 * 
	 * @param createdate
	 */
	public void setCreatedate(Date createdate)
	{
		this.createdate = createdate;
	}

	/**
	 * Method 'getCreateform'
	 * 
	 * @return String
	 */
	public String getCreateform()
	{
		return createform;
	}

	/**
	 * Method 'setCreateform'
	 * 
	 * @param createform
	 */
	public void setCreateform(String createform)
	{
		this.createform = createform;
	}

	/**
	 * Method 'getUpdatorid'
	 * 
	 * @return String
	 */
	public String getUpdatorid()
	{
		return updatorid;
	}

	/**
	 * Method 'setUpdatorid'
	 * 
	 * @param updatorid
	 */
	public void setUpdatorid(String updatorid)
	{
		this.updatorid = updatorid;
	}

	/**
	 * Method 'getUpdatedate'
	 * 
	 * @return Date
	 */
	public Date getUpdatedate()
	{
		return updatedate;
	}

	/**
	 * Method 'setUpdatedate'
	 * 
	 * @param updatedate
	 */
	public void setUpdatedate(Date updatedate)
	{
		this.updatedate = updatedate;
	}

	/**
	 * Method 'getUpdateform'
	 * 
	 * @return String
	 */
	public String getUpdateform()
	{
		return updateform;
	}

	/**
	 * Method 'setUpdateform'
	 * 
	 * @param updateform
	 */
	public void setUpdateform(String updateform)
	{
		this.updateform = updateform;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Xfactnoinfo)) {
			return false;
		}
		
		final Xfactnoinfo _cast = (Xfactnoinfo) _other;
		if (appactno == null ? _cast.appactno != appactno : !appactno.equals( _cast.appactno )) {
			return false;
		}
		
		if (appno == null ? _cast.appno != appno : !appno.equals( _cast.appno )) {
			return false;
		}
		
		if (startdate == null ? _cast.startdate != startdate : !startdate.equals( _cast.startdate )) {
			return false;
		}
		
		if (enddate == null ? _cast.enddate != enddate : !enddate.equals( _cast.enddate )) {
			return false;
		}
		
		if (actnostatus == null ? _cast.actnostatus != actnostatus : !actnostatus.equals( _cast.actnostatus )) {
			return false;
		}
		
		if (creatorid == null ? _cast.creatorid != creatorid : !creatorid.equals( _cast.creatorid )) {
			return false;
		}
		
		if (createdate == null ? _cast.createdate != createdate : !createdate.equals( _cast.createdate )) {
			return false;
		}
		
		if (createform == null ? _cast.createform != createform : !createform.equals( _cast.createform )) {
			return false;
		}
		
		if (updatorid == null ? _cast.updatorid != updatorid : !updatorid.equals( _cast.updatorid )) {
			return false;
		}
		
		if (updatedate == null ? _cast.updatedate != updatedate : !updatedate.equals( _cast.updatedate )) {
			return false;
		}
		
		if (updateform == null ? _cast.updateform != updateform : !updateform.equals( _cast.updateform )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (appactno != null) {
			_hashCode = 29 * _hashCode + appactno.hashCode();
		}
		
		if (appno != null) {
			_hashCode = 29 * _hashCode + appno.hashCode();
		}
		
		if (startdate != null) {
			_hashCode = 29 * _hashCode + startdate.hashCode();
		}
		
		if (enddate != null) {
			_hashCode = 29 * _hashCode + enddate.hashCode();
		}
		
		if (actnostatus != null) {
			_hashCode = 29 * _hashCode + actnostatus.hashCode();
		}
		
		if (creatorid != null) {
			_hashCode = 29 * _hashCode + creatorid.hashCode();
		}
		
		if (createdate != null) {
			_hashCode = 29 * _hashCode + createdate.hashCode();
		}
		
		if (createform != null) {
			_hashCode = 29 * _hashCode + createform.hashCode();
		}
		
		if (updatorid != null) {
			_hashCode = 29 * _hashCode + updatorid.hashCode();
		}
		
		if (updatedate != null) {
			_hashCode = 29 * _hashCode + updatedate.hashCode();
		}
		
		if (updateform != null) {
			_hashCode = 29 * _hashCode + updateform.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return XfactnoinfoPk
	 */
	public XfactnoinfoPk createPk()
	{
		return new XfactnoinfoPk(appactno);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "zt.cms.xf.common.dto.Xfactnoinfo: " );
		ret.append( "appactno=" + appactno );
		ret.append( ", appno=" + appno );
		ret.append( ", startdate=" + startdate );
		ret.append( ", enddate=" + enddate );
		ret.append( ", actnostatus=" + actnostatus );
		ret.append( ", creatorid=" + creatorid );
		ret.append( ", createdate=" + createdate );
		ret.append( ", createform=" + createform );
		ret.append( ", updatorid=" + updatorid );
		ret.append( ", updatedate=" + updatedate );
		ret.append( ", updateform=" + updateform );
		return ret.toString();
	}

}
