/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.factory;

import java.sql.Connection;
import zt.cms.xf.common.dao.*;
import zt.cms.xf.common.jdbc.*;

public class XfvcutpaydetlDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return XfvcutpaydetlDao
	 */
	public static XfvcutpaydetlDao create()
	{
		return new XfvcutpaydetlDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return XfvcutpaydetlDao
	 */
	public static XfvcutpaydetlDao create(Connection conn)
	{
		return new XfvcutpaydetlDaoImpl( conn );
	}

}
