/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.exceptions;

public class XfactpaydetlDaoException extends DaoException
{
	/**
	 * Method 'XfactpaydetlDaoException'
	 * 
	 * @param message
	 */
	public XfactpaydetlDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'XfactpaydetlDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public XfactpaydetlDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
