/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package zt.cms.xf.common.dao;

import zt.cms.xf.common.dto.Fdcutpaydetl;
import zt.cms.xf.common.dto.FdcutpaydetlPk;
import zt.cms.xf.common.exceptions.FdcutpaydetlDaoException;

import java.math.BigDecimal;
import java.util.Date;

public interface FdcutpaydetlDao
{
	/** 
	 * Inserts a new row in the FDCUTPAYDETL table.
	 */
	public FdcutpaydetlPk insert(Fdcutpaydetl dto) throws FdcutpaydetlDaoException;

	/** 
	 * Updates a single row in the FDCUTPAYDETL table.
	 */
	public void update(FdcutpaydetlPk pk, Fdcutpaydetl dto) throws FdcutpaydetlDaoException;

	/** 
	 * Deletes a single row in the FDCUTPAYDETL table.
	 */
	public void delete(FdcutpaydetlPk pk) throws FdcutpaydetlDaoException;

	/** 
	 * Returns the rows from the FDCUTPAYDETL table that matches the specified primary-key value.
	 */
	public Fdcutpaydetl findByPrimaryKey(FdcutpaydetlPk pk) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'SEQNO = :seqno'.
	 */
	public Fdcutpaydetl findByPrimaryKey(String seqno) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria ''.
	 */
	public Fdcutpaydetl[] findAll() throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'SEQNO = :seqno'.
	 */
	public Fdcutpaydetl[] findWhereSeqnoEquals(String seqno) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'XDKHZD_KHBH = :xdkhzdKhbh'.
	 */
	public Fdcutpaydetl[] findWhereXdkhzdKhbhEquals(String xdkhzdKhbh) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'XDKHZD_KHMC = :xdkhzdKhmc'.
	 */
	public Fdcutpaydetl[] findWhereXdkhzdKhmcEquals(String xdkhzdKhmc) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_HTBH = :gthtjhHtbh'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhHtbhEquals(String gthtjhHtbh) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_DATE = :gthtjhDate'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhDateEquals(String gthtjhDate) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_LL = :gthtjhLl'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhLlEquals(BigDecimal gthtjhLl) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_JHJE = :gthtjhJhje'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhJhjeEquals(BigDecimal gthtjhJhje) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_BJJE = :gthtjhBjje'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhBjjeEquals(BigDecimal gthtjhBjje) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_LXJE = :gthtjhLxje'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhLxjeEquals(BigDecimal gthtjhLxje) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTB_ZHBH = :gthtbZhbh'.
	 */
	public Fdcutpaydetl[] findWhereGthtbZhbhEquals(String gthtbZhbh) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'CUTPAYACTNO = :cutpayactno'.
	 */
	public Fdcutpaydetl[] findWhereCutpayactnoEquals(String cutpayactno) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'BILLSTATUS = :billstatus'.
	 */
	public Fdcutpaydetl[] findWhereBillstatusEquals(String billstatus) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'CREATETIME = :createtime'.
	 */
	public Fdcutpaydetl[] findWhereCreatetimeEquals(Date createtime) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'FAILREASON = :failreason'.
	 */
	public Fdcutpaydetl[] findWhereFailreasonEquals(String failreason) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'REMARK = :remark'.
	 */
	public Fdcutpaydetl[] findWhereRemarkEquals(String remark) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'PREFLAG = :preflag'.
	 */
	public Fdcutpaydetl[] findWherePreflagEquals(String preflag) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_HTNM = :gthtjhHtnm'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhHtnmEquals(String gthtjhHtnm) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'GTHTJH_JHXH = :gthtjhJhxh'.
	 */
	public Fdcutpaydetl[] findWhereGthtjhJhxhEquals(String gthtjhJhxh) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'JOURNALNO = :journalno'.
	 */
	public Fdcutpaydetl[] findWhereJournalnoEquals(String journalno) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'REGIONCD = :regioncd'.
	 */
	public Fdcutpaydetl[] findWhereRegioncdEquals(String regioncd) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'BANKCD = :bankcd'.
	 */
	public Fdcutpaydetl[] findWhereBankcdEquals(String bankcd) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the criteria 'LOCKSTATUS = :lockstatus'.
	 */
	public Fdcutpaydetl[] findWhereLockstatusEquals(String lockstatus) throws FdcutpaydetlDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the specified arbitrary SQL statement
	 */
	public Fdcutpaydetl[] findByDynamicSelect(String sql, Object[] sqlParams) throws FdcutpaydetlDaoException;

	/** 
	 * Returns all rows from the FDCUTPAYDETL table that match the specified arbitrary SQL statement
	 */
	public Fdcutpaydetl[] findByDynamicWhere(String sql, Object[] sqlParams) throws FdcutpaydetlDaoException;

}
